import { spawnSync } from 'child_process';
import path from 'path';

const scenarios = [
  { router: 'account', path: '/me' },
  { router: 'account', path: '/me/sessions' },
  { router: 'account', path: '/account/security-log' },
  { router: 'admin', path: '/admin/clients' },
  { router: 'adminAuditLog', path: '/admin/audit-log' },
  { router: 'adminUsers', path: '/admin/users' },
  { router: 'adminUsers', path: '/admin/users/fixture-user' },
  { router: 'adminWallets', path: '/admin/wallets' },
  { router: 'adminWithdrawals', path: '/admin/withdrawals' },
  { router: 'apiKeys', path: '/api-keys' },
  { router: 'candles', path: '/candles/BTC%2FUSDT' },
  { router: 'card', path: '/card/waitlist/me' },
  { router: 'cfd', path: '/cfd/positions' },
  { router: 'cfd', path: '/cfd/positions/history' },
  { router: 'demoTrading', path: '/demo/balances' },
  { router: 'demoTrading', path: '/demo/orders/open' },
  { router: 'demoTrading', path: '/demo/trades/BTC%2FUSDT' },
  { router: 'deposits', path: '/deposits/me' },
  { router: 'kyc', path: '/kyc/me' },
  { router: 'marketData', path: '/market/tradable' },
  { router: 'marketData', path: '/market/ticker/BTC-USDT' },
  { router: 'portfolio', path: '/wallet/overview' },
  { router: 'portfolio', path: '/wallet/performance' },
  { router: 'portfolio', path: '/wallet/portfolio-history' },
  { router: 'products', path: '/products' },
  { router: 'products', path: '/purchases/me' },
  { router: 'referral', path: '/referral/me' },
  { router: 'trades', path: '/trades/me' },
  { router: 'withdrawals', path: '/withdrawals/me' },
  { router: 'adminUsers', path: '/admin/users', adminFailure: true },
  { router: 'trades', path: '/trades/me', apiKey: true },
  { router: 'reserves', path: '/reserves', configuredTreasury: true },
  { router: 'deposits', method: 'post', path: '/deposits/claim/bitcoin', configuredTreasury: true,
    body: { asset: 'BTC', txHash: 'a'.repeat(64) } },
  { router: 'account', method: 'patch', path: '/me/profile', body: { displayName: 'Fixture' } },
  { router: 'account', method: 'delete', path: '/me/avatar' },
  { router: 'account', method: 'patch', path: '/me/password', body: { currentPassword: 'fixture', newPassword: 'FixtureOnly123' } },
  { router: 'account', method: 'delete', path: '/me/sessions/other-session' },
  { router: 'account', method: 'post', path: '/account/2fa/setup' },
  { router: 'account', method: 'post', path: '/account/2fa/verify', body: { code: '123456' } },
  { router: 'account', method: 'post', path: '/account/2fa/disable', body: { code: '123456' } },
  { router: 'adminUsers', method: 'post', path: '/admin/users/fixture-user/block', body: { reason: 'Fixture' } },
  { router: 'adminUsers', method: 'post', path: '/admin/users/fixture-user/unblock' },
  { router: 'adminWallets', method: 'put', path: '/admin/wallets/bitcoin', body: { address: 'fixture-no-network' } },
  { router: 'adminWallets', method: 'delete', path: '/admin/wallets/bitcoin' },
  { router: 'apiKeys', method: 'post', path: '/api-keys', body: { label: 'Fixture' } },
  { router: 'apiKeys', method: 'delete', path: '/api-keys/fixture-key' },
  { router: 'auth', method: 'post', path: '/auth/register', body: { email: 'fixture@example.invalid', password: 'FixtureOnly123' } },
  { router: 'auth', method: 'post', path: '/auth/login', body: { email: 'fixture@example.invalid', password: 'FixtureOnly123' } },
  { router: 'auth', method: 'post', path: '/auth/login/2fa', pending2fa: true },
  { router: 'demoTrading', method: 'delete', path: '/demo/orders/fixture-order' },
  { router: 'portfolio', method: 'post', path: '/wallet/portfolio-snapshot', body: { totalValueUsd: '100' } },
  { router: 'account', method: 'put', path: '/me/avatar', body: { image: 'data:image/png;base64,iVBORw0KGgo=' } },
  { router: 'products', path: '/admin/products' },
  { router: 'products', method: 'post', path: '/products', body: { name: 'Fixture', description: 'Fixture product', priceAmount: '10', priceAsset: 'USDT' } },
  { router: 'products', method: 'delete', path: '/products/fixture-product' },
  { router: 'adminDeposits', method: 'post', path: '/admin/deposits/ignore', body: { chain: 'bitcoin', txHash: 'fixture-hash' } },
  { router: 'kyc', path: '/kyc/admin/delivery' },
  { router: 'kyc', path: '/kyc/fixture-submission/document' },
  { router: 'kyc', method: 'post', path: '/kyc/fixture-submission/review', body: { approve: false, reason: 'Fixture' } },
  { router: 'kyc', method: 'post', path: '/internal/kyc/authorize', edgeFailure: true },
] as const;

it.each(scenarios)('contains a dependency rejection in $router $path ($adminFailure $apiKey)', scenario => {
  const child = spawnSync(process.execPath, ['--unhandled-rejections=strict',
    path.join(__dirname, 'fixtures/asyncFailureServer.cjs'), JSON.stringify(scenario)],
  { encoding: 'utf8', timeout: 15_000, env: { ...process.env, NODE_ENV: 'test' } });
  expect({ exit: child.status, stderr: child.stderr, error: child.error?.message }).toEqual({ exit: 0, stderr: '', error: undefined });
  const result = JSON.parse(child.stdout.trim().split('\n').at(-1)!);
  expect(result).toEqual({ status: 500, body: { error: 'Internal server error' },
    forwarded: 1, attempts: expect.any(Number), health: { status: 'ok' } });
  expect(result.attempts).toBeGreaterThan(0);
}, 20_000);
