import test from 'node:test';import assert from 'node:assert/strict';
import {createState,applyQuote,submit,cancel,validate,snapshot,setBalances,quoteStatus} from './engine.mjs';
import {convertPrices,composeRubUsdcFx,parseCandles,MarketHub} from './market.mjs';
const now=1791569400000,A='BYBIT:AAPLXUSDT',B='BINANCE:AAPLBUSDT',R='MOEX:TQBR:SBER';let serial=0;

const q=(id=A,time=now,price='100',eventId=String(++serial))=>({instrumentId:id,provider:id.startsWith('MOEX')?'moex':id.startsWith('BINANCE')?'binance':'bybit',nativeCurrency:id===R?'RUB':'USDT',bid:price,ask:price,last:price,timestamp:time,receivedAt:time,verified:true,marketOpen:true,eventId,capacity:'1.00000000',prices:{USDT:{buy:price,sell:price},USDC:{buy:price,sell:price}},fx:{USDC:{rate:'1',timestamp:time,maxAgeMs:180000,source:'unit fixture'},...(id===R?{USDT:{rate:'1',timestamp:time+900000,stableTimestamp:time+900000,maxAgeMs:129600000,source:'unit fixture'}}:{})},multiplier:'1.0032690125398187'});
const order=(overrides={})=>({id:`request-${String(++serial).padStart(20,'0')}`,instrumentId:A,currency:'USDT',side:'BUY',type:'MARKET',quantity:'0.5',...overrides});
test('fractional Apple buy, revaluation, half/full sale reconcile weighted entry and native chart entry',()=>{const s=createState(now);applyQuote(s,q(),now);submit(s,order(),now);assert.equal(s.wallets.USDT.cash,'9950.00000000');applyQuote(s,q(A,now+1,'120'),now+1);submit(s,order({quantity:'0.5'}),now+1);let p=snapshot(s,now+1).positions[A+'|USDT'];assert.equal(p.average,'110.00000000');assert.equal(p.averageNative,'110.00000000');assert.equal(p.unrealized,'10.00000000');submit(s,order({side:'SELL',quantity:'0.5'}),now+1);applyQuote(s,q(A,now+2,'90'),now+2);submit(s,order({side:'SELL',quantity:'0.5'}),now+2);assert.equal(s.realized.USDT,'-5.00000000');assert.equal(s.wallets.USDT.cash,'9995.00000000');assert.equal(s.positions[A+'|USDT'].nativeCost,'0.00000000');validate(s);});
test('partial GTC reserves remaining cost, replay cannot refill, cancel only releases remainder',()=>{const s=createState(now);const o=submit(s,order({type:'LIMIT',quantity:'2.5',limitPrice:'101'}),now);assert.equal(s.wallets.USDT.reserved,'252.50000000');const quote=q(A,now+1);applyQuote(s,quote,now+1);assert.equal(o.status,'PARTIAL');assert.equal(o.filled,'1.00000000');assert.equal(s.wallets.USDT.reserved,'151.50000000');applyQuote(s,{...quote,receivedAt:now+2},now+2);assert.equal(s.fills.length,1);applyQuote(s,q(A,now+3),now+3);assert.equal(o.filled,'2.00000000');cancel(s,o.id,now+4);assert.equal(o.status,'PARTIAL_CANCELLED');assert.equal(s.wallets.USDT.reserved,'0.00000000');assert.equal(s.wallets.USDT.cash,'9800.00000000');validate(s);});
test('Market IOC partially fills model capacity then cancels unfilled quantity',()=>{const s=createState();applyQuote(s,q(),now);const o=submit(s,order({quantity:'3'}),now);assert.equal(o.status,'PARTIAL_CANCELLED');assert.equal(o.filled,'1.00000000');assert.equal(s.wallets.USDT.reserved,'0.00000000');validate(s);});
test('Limit ignores any pre-placement crossing, including newly received delayed historical observations',()=>{const s=createState();submit(s,order({type:'LIMIT',limitPrice:'200'}),now);applyQuote(s,q(A,now-1),now);assert.equal(s.fills.length,0);applyQuote(s,q(A,now+1),now+1);assert.equal(s.fills.length,1);});
test('source identity separates AAPLB, AAPLX and their wallets; oversell is blocked',()=>{const s=createState();applyQuote(s,q(),now);submit(s,order(),now);applyQuote(s,q(B),now);assert.throws(()=>submit(s,order({instrumentId:B,side:'SELL'}),now),/INSUFFICIENT_SHARES/);assert.throws(()=>submit(s,order({currency:'USDC',side:'SELL'}),now),/INSUFFICIENT_SHARES/);validate(s);});
test('duplicate IDs are canonical and cannot duplicate fills or change payload',()=>{const s=createState();applyQuote(s,q(),now);const o=order();submit(s,o,now);submit(s,{...o,quantity:'0.50000000'},now);assert.equal(s.fills.length,1);assert.throws(()=>submit(s,{...o,quantity:'0.6'},now),/IDEMPOTENCY_CONFLICT/);});
test('stale, failed, future, unverified and closed quotes cannot execute or produce a fake PnL',()=>{for(const change of [{timestamp:now-61000},{failed:true},{timestamp:now+10000},{verified:false},{marketOpen:false}]){const s=createState();applyQuote(s,{...q(),...change},now);assert.throws(()=>submit(s,order(),now));assert.equal(s.fills.length,0);}});
test('SBER RUB conversion with non-parity USDC, correct realised PnL, both FX timestamps audited',()=>{const s=createState();const r=q(R,now-900000,'320');r.receivedAt=now;r.prices={USDT:convertPrices('320','320','80'),USDC:convertPrices('320','320','88')};r.fx={USDT:{rate:'80',timestamp:now-900000,stableTimestamp:now,maxAgeMs:129600000,source:'unit fixture'},USDC:{rate:'88',timestamp:now,maxAgeMs:180000,referenceTimestamp:now-900000,stableTimestamp:now,source:'unit fixture'}};applyQuote(s,r,now);submit(s,order({instrumentId:R,currency:'USDC',quantity:'0.5'}),now);assert.equal(s.wallets.USDC.cash,'9998.18181818');assert.equal(s.wallets.USDT.cash,'10000.00000000');assert.equal(s.fills[0].nativePrice,'320');assert.equal(s.fills[0].fx.rate,'88');const next={...r,bid:'352',ask:'352',timestamp:now-899999,eventId:'next',prices:{USDT:convertPrices('352','352','80'),USDC:convertPrices('352','352','88')}};applyQuote(s,next,now+1);submit(s,order({instrumentId:R,currency:'USDC',side:'SELL',quantity:'0.5'}),now+1);assert.equal(s.realized.USDC,'0.18181818');validate(s);});
test('SBER fails closed for missing RUB FX, stale daily reference or stale stablecoin leg',()=>{const quote=q(R);delete quote.prices.USDT;assert.equal(quoteStatus(quote,now),'FX_UNAVAILABLE');quote.prices.USDT={buy:'1',sell:'1'};quote.fx.USDT={timestamp:now,maxAgeMs:180000,referenceTimestamp:now-129600001};assert.equal(quoteStatus(quote,now),'FX_STALE');quote.fx.USDT={timestamp:now,maxAgeMs:129600000,stableTimestamp:now-180001};assert.equal(quoteStatus(quote,now),'FX_STALE');});
test('pending SBER limit cannot use a 15 minute delayed observation from before placement',()=>{const s=createState();submit(s,order({instrumentId:R,type:'LIMIT',limitPrice:'500'}),now);applyQuote(s,{...q(R,now-900000,'320'),receivedAt:now},now);assert.equal(s.fills.length,0);applyQuote(s,{...q(R,now+1,'320'),receivedAt:now+900001},now+900001);assert.equal(s.fills.length,1);validate(s);});
test('audited capital edits cannot consume reserved cash or change historical PnL',()=>{const s=createState();submit(s,order({type:'LIMIT',limitPrice:'100'}),now);assert.throws(()=>setBalances(s,{id:'capital-111111111111',balances:{USDT:'1',USDC:'1'}},now),/RESERVED_FUNDS/);setBalances(s,{id:'capital-222222222222',balances:{USDT:'12000',USDC:'11000'}},now);assert.equal(s.adjustments.length,1);assert.equal(s.realized.USDT,'0.00000000');validate(s);});
test('candles preserve actual gaps, sort/deduplicate and reject false OHLC or future bars',()=>{assert.deepEqual(parseCandles([[now-60000,'1','3','1','2','4'],[now-180000,'1','2','1','1','0']],'binance',now).map(c=>c.time),[(now-180000)/1000,(now-60000)/1000]);assert.throws(()=>parseCandles([[now,'5','3','1','2','4']],'binance',now),/INVALID_CANDLES/);assert.throws(()=>parseCandles([[now+60000,'1','3','1','2','4']],'binance',now),/INVALID_CANDLES/);});
test('no MOEX minute candles can be obtained by interpolation from daily source',async()=>{const h=new MarketHub({fetchImpl:()=>{throw Error('unexpected network');}});await assert.rejects(h.history(R,'5m'),/UNSUPPORTED_TIMEFRAME/);});
test('read-only adapter rejects arbitrary hosts and coalesces/cache hits',async()=>{let calls=0;const h=new MarketHub({fetchImpl:async(url,opts)=>{calls++;assert.equal(opts.method,'GET');return new Response('{"ok":true}');},now:()=>now});await assert.rejects(h.request('https://evil.invalid/api'),/SOURCE_FORBIDDEN/);const url='https://api.binance.com/api/v3/time';await Promise.all([h.request(url,1000),h.request(url,1000)]);await h.request(url,1000);assert.equal(calls,1);});
test('actual token price is not multiplied twice; multiplier remains audit metadata',()=>{const s=createState();const v=q();v.multiplier='1.25';applyQuote(s,v,now);submit(s,order(),now);assert.equal(s.wallets.USDT.cash,'9950.00000000');assert.equal(s.fills[0].multiplier,'1.25');});

test("converted prices without independently verified FX cannot execute",()=>{const quote=q();delete quote.fx.USDC;assert.equal(quoteStatus(quote,now,"USDC"),"FX_UNAVAILABLE");quote.fx.USDC={rate:"1.001",timestamp:now};assert.equal(quoteStatus(quote,now,"USDC"),"FX_STALE");quote.fx.USDC.maxAgeMs=180000;assert.equal(quoteStatus(quote,now,"USDC"),"READY");quote.fx.USDC.rate="0";assert.equal(quoteStatus(quote,now,"USDC"),"FX_UNAVAILABLE");});

test('RUB/USDC audit retains both conversion legs and the actual native rate',()=>{
  const rub={rate:'80',timestamp:now-900000,stableTimestamp:now,maxAgeMs:129600000,source:'reference fixture'},
    usdc={rate:'1.1',timestamp:now,maxAgeMs:180000,source:'stablecoin fixture'};
  const fx=composeRubUsdcFx(rub,usdc);assert.equal(fx.rate,'88.00000000');assert.deepEqual(fx.legs,[rub,usdc]);
  const state=createState(),quote=q(R,now-900000,'352');quote.receivedAt=now;
  quote.prices.USDC=convertPrices('352','352',fx.rate);quote.fx.USDC=fx;
  applyQuote(state,quote,now);submit(state,order({instrumentId:R,currency:'USDC',quantity:'0.5'}),now);
  assert.equal(state.wallets.USDC.cash,'9998.00000000');assert.deepEqual(state.fills[0].fx,fx);validate(state);
});
