import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createServer} from './server.mjs';import {openStore} from './store.mjs';import {submit,applyQuote} from './engine.mjs';import {CATALOG} from './catalog.mjs';
const now=1791569400000,id='BYBIT:AAPLXUSDT';const fixture={instrumentId:id,provider:'bybit',nativeCurrency:'USDT',bid:'100',ask:'100',timestamp:now,receivedAt:now,verified:true,marketOpen:true,eventId:'fixture-only-1',capacity:'1.00000000',prices:{USDT:{buy:'100',sell:'100'}},fx:{}};
const order=(n)=>({id:`request-${String(n).padStart(20,'0')}`,instrumentId:id,currency:'USDT',side:'BUY',type:'MARKET',quantity:'0.1'});
test('HTTP allows only isolated paper mutations; rejects CSRF, real order routes and forged quote endpoints',async()=>{const d=await mkdtemp(join(tmpdir(),'voltex-stocks-global-'));const hub={metrics:{},catalogue:async()=>CATALOG,quote:async()=>fixture,history:async()=>({candles:[]})};const app=await createServer({port:0,dataPath:join(d,'ledger.json'),hub,now:()=>now,autoPoll:false});try{await app.refresh(id);const base=`http://127.0.0.1:${app.port}`;let state=await(await fetch(base+'/__stocks_global/state')).json();const post=(path,body,headers={})=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json','X-Stocks-Token':state.token,...headers},body:JSON.stringify(body)});
  assert.equal((await post('/__stocks_global/orders',order(1),{Origin:'https://evil.invalid'})).status,422);assert.equal((await post('/__stocks_global/orders',order(1),{'X-Stocks-Token':'wrong'})).status,422);
  for(const path of ['/api/orders','/api/wallet/balance','/v1/orders','/admin/users','/__stocks_simulator/orders','/__stocks_global/quote','/__stocks_global/reset'])assert.equal((await post(path,{price:'0.01'})).status,404);
  const responses=await Promise.all(Array.from({length:20},(_,n)=>post('/__stocks_global/orders',order(n+1))));assert.ok(responses.every(r=>r.status===200));state=await(await fetch(base+'/__stocks_global/state')).json();assert.equal(state.fills.length,10);assert.equal(state.wallets.USDT.cash,'9900.00000000');assert.equal(state.wallets.USDT.reserved,'0.00000000');assert.equal((await post('/__stocks_global/orders',order(1))).status,200);assert.equal((await(await fetch(base+'/__stocks_global/state')).json()).fills.length,10);
  await post('/__stocks_global/balances',{id:'capital-1111111111111',balances:{USDT:'12000',USDC:'10000'}});assert.equal((await(await fetch(base+'/__stocks_global/state')).json()).adjustments.length,1);
}finally{await app.close();await rm(d,{recursive:true,force:true});}});
test('atomic JSON ledger survives restart with reservation/history, refuses second writer',async()=>{const d=await mkdtemp(join(tmpdir(),'voltex-stocks-global-'));const path=join(d,'ledger.json');let store=await openStore(path,{now:()=>now});try{await assert.rejects(openStore(path),/EEXIST/);await store.transact(s=>{applyQuote(s,fixture,now);submit(s,order(1),now);submit(s,{...order(2),type:'LIMIT',limitPrice:'90'},now);});await store.close();store=await openStore(path,{now:()=>now});const s=store.read();assert.equal(s.fills.length,1);assert.equal(s.orders.length,2);assert.equal(s.wallets.USDT.reserved,'9.00000000');assert.equal(s.wallets.USDT.cash,'9990.00000000');assert.equal(JSON.parse(await readFile(path)).schema,2);}finally{await store.close();await rm(d,{recursive:true,force:true});}});
test('failed persistence cannot debit or publish a fill',async()=>{const d=await mkdtemp(join(tmpdir(),'voltex-stocks-global-'));let writes=0;const store=await openStore(join(d,'ledger.json'),{now:()=>now,persist:async()=>{if(++writes>1)throw Error('DISK_FULL');}});try{await assert.rejects(store.transact(s=>{applyQuote(s,fixture,now);submit(s,order(1),now);}),/DISK_FULL/);assert.equal(store.read().fills.length,0);assert.equal(store.read().wallets.USDT.cash,'10000.00000000');}finally{await store.close();await rm(d,{recursive:true,force:true});}});

test("V2 refuses an existing V1 ledger without modifying it",async()=>{const d=await mkdtemp(join(tmpdir(),"voltex-stocks-global-"));const path=join(d,"v1.json");const original=JSON.stringify({schema:1,revision:0,orders:[],fills:[]});try{await writeFile(path,original);await assert.rejects(openStore(path),/CORRUPT_LEDGER/);assert.equal(await readFile(path,"utf8"),original);}finally{await rm(d,{recursive:true,force:true});}});
