import { createHash } from 'crypto';
import bcrypt from 'bcrypt';
import legacy from './fixtures/bcrypt-5.1.1-compatibility.json';
import { generateBackupCodes, verifyAndConsume2FACode } from '../TwoFactorService';

// These are public, non-production fixture passwords generated by the actual
// bcrypt 5.1.1 native package before migration. Do not regenerate them with 6:
// the unchanged old bytes are the migration compatibility boundary.
const passwords = legacy.fixtures.filter(fixture => fixture.purpose === 'password');
const backupCodes = legacy.fixtures.filter(fixture => fixture.purpose === 'backup-code');

describe('bcrypt 5.1.1 -> 6.0.0 controlled compatibility', () => {
  it('uses the reviewed bcrypt 6 native package and immutable legacy fixture provenance', () => {
    expect(require('bcrypt/package.json').version).toBe('6.0.0');
    expect(jest.isMockFunction(bcrypt.hash)).toBe(false);
    expect(jest.isMockFunction(bcrypt.compare)).toBe(false);
    expect(legacy.provenance.generatorVersion).toBe('5.1.1');
    expect(legacy.provenance.sourceMainSha).toBe('27d531b0140471654adf3f18203b06de73ed5598');
    expect(createHash('sha256').update(JSON.stringify(legacy.fixtures)).digest('hex'))
      .toBe(legacy.provenance.fixturesSha256);
    expect(passwords).toHaveLength(6);
    expect(backupCodes).toHaveLength(2);
    for (const fixture of legacy.fixtures) {
      expect(Buffer.byteLength(fixture.password, 'utf8')).toBe(fixture.utf8Bytes);
      expect(bcrypt.getRounds(fixture.hash)).toBe(fixture.cost);
      expect(fixture.cost).toBe(fixture.purpose === 'password' ? 12 : 10);
    }
  });

  it.each(legacy.fixtures)('verifies correct and rejects wrong input for old $id without rehashing it', async fixture => {
    const originalHash = fixture.hash;
    await expect(bcrypt.compare(fixture.password, originalHash)).resolves.toBe(true);
    await expect(bcrypt.compare(fixture.wrongPassword, originalHash)).resolves.toBe(false);
    // Reusing the old salt also proves equivalent native hash computation,
    // including the explicitly generated $2a$ compatibility fixture.
    await expect(bcrypt.hash(fixture.password, originalHash)).resolves.toBe(originalHash);
    expect(fixture.hash).toBe(originalHash);
  });

  it.each(passwords)('new bcrypt 6 hash preserves cost 12 and correct/wrong semantics for $id', async fixture => {
    const hash = await bcrypt.hash(fixture.password, 12);
    expect(hash).toMatch(/^\$2b\$12\$/);
    expect(bcrypt.getRounds(hash)).toBe(12);
    await expect(bcrypt.compare(fixture.password, hash)).resolves.toBe(true);
    await expect(bcrypt.compare(fixture.wrongPassword, hash)).resolves.toBe(false);
  });

  it.each(passwords.filter(fixture => fixture.aliases))('keeps the existing 72-byte boundary for $id', async fixture => {
    expect(Buffer.byteLength(fixture.password, 'utf8')).toBe(72);
    const freshHash = await bcrypt.hash(fixture.password, 12);
    for (const alias of fixture.aliases ?? []) {
      expect(Buffer.byteLength(alias, 'utf8')).toBeGreaterThan(72);
      // bcrypt has always ignored bytes beyond 72; this migration must not
      // silently change existing users' accepted passwords or their policy.
      await expect(bcrypt.compare(alias, fixture.hash)).resolves.toBe(true);
      await expect(bcrypt.compare(alias, freshHash)).resolves.toBe(true);
    }
  });

  it('preserves embedded NUL bytes rather than treating them as a string terminator', async () => {
    const fixture = passwords.find(value => value.id === 'password-embedded-nul')!;
    expect(fixture.password).toContain('\u0000');
    const freshHash = await bcrypt.hash(fixture.password, 12);
    for (const prefixOnly of fixture.rejectedAliases ?? []) {
      await expect(bcrypt.compare(prefixOnly, fixture.hash)).resolves.toBe(false);
      await expect(bcrypt.compare(prefixOnly, freshHash)).resolves.toBe(false);
    }
  });

  it('normalizes and consumes a real legacy backup hash once while preserving the remaining hash', async () => {
    const [first, second] = backupCodes;
    const user = { twoFactorSecret: null, twoFactorBackupCodes: [first.hash, second.hash] };
    const result = await verifyAndConsume2FACode(user, `  ${first.password.toLowerCase()}  `);
    expect(result).toEqual({ ok: true, remainingBackupCodes: [second.hash] });
    expect(user.twoFactorBackupCodes).toEqual([first.hash, second.hash]);
    // The actual caller persists this returned array. Simulate that local
    // transition, not a production database write.
    const afterConsumption = { ...user, twoFactorBackupCodes: result.remainingBackupCodes! };
    await expect(verifyAndConsume2FACode(afterConsumption, first.password)).resolves.toEqual({ ok: false });
    await expect(verifyAndConsume2FACode(afterConsumption, second.password))
      .resolves.toEqual({ ok: true, remainingBackupCodes: [] });
  });

  it('rejects an incorrect backup code without returning consumed state', async () => {
    const user = { twoFactorSecret: null, twoFactorBackupCodes: backupCodes.map(value => value.hash) };
    await expect(verifyAndConsume2FACode(user, 'WRNG-CODE')).resolves.toEqual({ ok: false });
    expect(user.twoFactorBackupCodes).toEqual(backupCodes.map(value => value.hash));
  });

  it('keeps generation at eight cost-10 bcrypt 6 backup hashes with normalization and consumption', async () => {
    const generated = await generateBackupCodes();
    expect(generated.plaintext).toHaveLength(8);
    expect(generated.hashed).toHaveLength(8);
    for (let index = 0; index < 8; index++) {
      expect(generated.plaintext[index]).toMatch(/^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{4}-[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{4}$/);
      expect(bcrypt.getRounds(generated.hashed[index])).toBe(10);
      await expect(bcrypt.compare(generated.plaintext[index], generated.hashed[index])).resolves.toBe(true);
      await expect(bcrypt.compare('WRNG-CODE', generated.hashed[index])).resolves.toBe(false);
    }
    const result = await verifyAndConsume2FACode(
      { twoFactorSecret: null, twoFactorBackupCodes: generated.hashed },
      `\t${generated.plaintext[0].toLowerCase()}\n`,
    );
    expect(result).toEqual({ ok: true, remainingBackupCodes: generated.hashed.slice(1) });
  });
});
