import type { Lang } from '../../lib/i18n';

const en = {
  eyebrow: 'GLOBAL TRADING SESSIONS', title: 'The market never sleeps.', titleEnd: 'Its centre moves.',
  description: 'Crypto trades 24/7. Global market activity follows Asia, Europe and the USA.',
  current: 'Current session', next: 'Next session', overlap: 'Session overlap', nextOverlap: 'Next overlap',
  noActive: 'Between session windows', noOverlap: 'No overlap scheduled', opens: 'Opens in', closes: 'Closes in', starts: 'Starts in', ends: 'Ends in',
  active: 'ACTIVE', upcoming: 'UPCOMING', closed: 'CLOSED', localTime: 'Local time', anchorTime: 'Anchor city time',
  window: 'Local session window', elapsed: 'Session time elapsed', map: 'Global session map',
  activeKey: 'Active window', inactiveKey: 'Outside window', crypto: 'CRYPTO · OPEN 24/7',
  note: 'Indicative weekday activity windows, not exchange opening hours or a holiday calendar. Crypto remains open 24/7. Local times adjust automatically for daylight saving time.',
  overlapNote: 'Two regional activity windows coincide.', pause: 'Pause map motion', resume: 'Resume map motion',
  cities: { Tokyo: 'Tokyo', 'Hong Kong': 'Hong Kong', Singapore: 'Singapore', London: 'London', Frankfurt: 'Frankfurt', Zürich: 'Zürich', 'New York': 'New York' },
};

export const TRADING_SESSIONS_COPY: Record<Lang, typeof en> = {
  en,
  ru: {
    eyebrow: 'ГЛОБАЛЬНЫЕ ТОРГОВЫЕ СЕССИИ', title: 'Рынок не спит.', titleEnd: 'Меняется его центр.',
    description: 'Криптовалюты торгуются 24/7, но активность мировых рынков меняется вместе с Азией, Европой и США.',
    current: 'Текущая сессия', next: 'Следующая сессия', overlap: 'Пересечение сессий', nextOverlap: 'Следующее пересечение',
    noActive: 'Между окнами сессий', noOverlap: 'Пересечение не запланировано', opens: 'Откроется через', closes: 'Закроется через', starts: 'Начнётся через', ends: 'Завершится через',
    active: 'АКТИВНА', upcoming: 'ВПЕРЕДИ', closed: 'ЗАКРЫТА', localTime: 'Местное время', anchorTime: 'Время опорного города',
    window: 'Окно по местному времени', elapsed: 'Прошедшее время сессии', map: 'Карта глобальных сессий',
    activeKey: 'Активное окно', inactiveKey: 'Вне окна', crypto: 'КРИПТО · ОТКРЫТО 24/7',
    note: 'Ориентировочные окна активности по будням, а не часы работы бирж или календарь праздников. Криптовалюты доступны 24/7. Местное время автоматически учитывает переход на летнее и зимнее время.',
    overlapNote: 'Совпадают окна активности двух регионов.', pause: 'Приостановить движение карты', resume: 'Продолжить движение карты',
    cities: { Tokyo: 'Токио', 'Hong Kong': 'Гонконг', Singapore: 'Сингапур', London: 'Лондон', Frankfurt: 'Франкфурт', Zürich: 'Цюрих', 'New York': 'Нью-Йорк' },
  },
  es: {
    eyebrow: 'SESIONES GLOBALES DE TRADING', title: 'El mercado nunca duerme.', titleEnd: 'Su centro cambia.',
    description: 'Las criptomonedas cotizan 24/7. La actividad global sigue a Asia, Europa y Estados Unidos.',
    current: 'Sesión actual', next: 'Próxima sesión', overlap: 'Solapamiento de sesiones', nextOverlap: 'Próximo solapamiento',
    noActive: 'Entre ventanas de sesión', noOverlap: 'Sin solapamiento previsto', opens: 'Abre en', closes: 'Cierra en', starts: 'Empieza en', ends: 'Termina en',
    active: 'ACTIVA', upcoming: 'PRÓXIMA', closed: 'CERRADA', localTime: 'Hora local', anchorTime: 'Hora de la ciudad de referencia',
    window: 'Ventana en hora local', elapsed: 'Tiempo de sesión transcurrido', map: 'Mapa de sesiones globales',
    activeKey: 'Ventana activa', inactiveKey: 'Fuera de ventana', crypto: 'CRYPTO · ABIERTO 24/7',
    note: 'Ventanas orientativas de actividad entre semana; no son horarios de bolsas ni un calendario festivo. Las criptomonedas siguen abiertas 24/7. Las horas locales se ajustan automáticamente al horario de verano.',
    overlapNote: 'Coinciden dos ventanas de actividad regional.', pause: 'Pausar movimiento del mapa', resume: 'Reanudar movimiento del mapa',
    cities: { Tokyo: 'Tokio', 'Hong Kong': 'Hong Kong', Singapore: 'Singapur', London: 'Londres', Frankfurt: 'Fráncfort', Zürich: 'Zúrich', 'New York': 'Nueva York' },
  },
  zh: {
    eyebrow: '全球交易时段', title: '市场从不休眠。', titleEnd: '交易中心不断转移。',
    description: '加密货币全天候交易，全球市场活跃时段则随亚洲、欧洲和美国依次变化。',
    current: '当前时段', next: '下一时段', overlap: '时段重叠', nextOverlap: '下次重叠',
    noActive: '处于时段间隔', noOverlap: '暂无重叠时段', opens: '距开始', closes: '距结束', starts: '距开始', ends: '距结束',
    active: '活跃', upcoming: '即将开始', closed: '已结束', localTime: '当地时间', anchorTime: '基准城市时间',
    window: '当地时段', elapsed: '时段已过时间', map: '全球交易时段地图',
    activeKey: '活跃时段', inactiveKey: '时段之外', crypto: '加密货币 · 全天候开放',
    note: '这是工作日的参考活跃时段，并非交易所营业时间或节假日日历。加密货币始终全天候开放。当地时间自动适用夏令时。',
    overlapNote: '两个地区的活跃时段重叠。', pause: '暂停地图动画', resume: '继续地图动画',
    cities: { Tokyo: '东京', 'Hong Kong': '香港', Singapore: '新加坡', London: '伦敦', Frankfurt: '法兰克福', Zürich: '苏黎世', 'New York': '纽约' },
  },
  hi: {
    eyebrow: 'वैश्विक ट्रेडिंग सत्र', title: 'बाज़ार कभी नहीं सोता।', titleEnd: 'उसका केंद्र बदलता है।',
    description: 'क्रिप्टो में 24/7 कारोबार होता है। वैश्विक बाज़ार की गतिविधि एशिया, यूरोप और अमेरिका के साथ बदलती है।',
    current: 'वर्तमान सत्र', next: 'अगला सत्र', overlap: 'सत्रों का मेल', nextOverlap: 'अगला मेल',
    noActive: 'सत्रों के बीच का समय', noOverlap: 'कोई मेल निर्धारित नहीं', opens: 'शुरू होने में', closes: 'समाप्त होने में', starts: 'शुरू होने में', ends: 'समाप्त होने में',
    active: 'सक्रिय', upcoming: 'आगामी', closed: 'बंद', localTime: 'स्थानीय समय', anchorTime: 'संदर्भ शहर का समय',
    window: 'स्थानीय सत्र अवधि', elapsed: 'सत्र का बीता समय', map: 'वैश्विक सत्र मानचित्र',
    activeKey: 'सक्रिय अवधि', inactiveKey: 'अवधि से बाहर', crypto: 'क्रिप्टो · 24/7 खुला',
    note: 'ये कार्यदिवसों की अनुमानित गतिविधि अवधियाँ हैं, एक्सचेंज के खुलने का समय या छुट्टियों का कैलेंडर नहीं। क्रिप्टो 24/7 खुला रहता है। स्थानीय समय अपने आप डेलाइट सेविंग के अनुसार बदलता है।',
    overlapNote: 'दो क्षेत्रों की गतिविधि अवधियाँ एक साथ हैं।', pause: 'मानचित्र की गति रोकें', resume: 'मानचित्र की गति जारी रखें',
    cities: { Tokyo: 'टोक्यो', 'Hong Kong': 'हांगकांग', Singapore: 'सिंगापुर', London: 'लंदन', Frankfurt: 'फ़्रैंकफ़र्ट', Zürich: 'ज़्यूरिख', 'New York': 'न्यूयॉर्क' },
  },
  ja: {
    eyebrow: 'グローバル取引セッション', title: '市場は眠らない。', titleEnd: 'その中心が移り変わる。',
    description: '暗号資産は24時間365日取引され、世界の市場活動はアジア、欧州、米国へと移り変わります。',
    current: '現在のセッション', next: '次のセッション', overlap: 'セッションの重複', nextOverlap: '次の重複時間',
    noActive: 'セッションの時間外', noOverlap: '重複の予定なし', opens: '開始まで', closes: '終了まで', starts: '開始まで', ends: '終了まで',
    active: '進行中', upcoming: '開始前', closed: '終了', localTime: '現地時間', anchorTime: '基準都市の時間',
    window: '現地のセッション時間', elapsed: 'セッション経過時間', map: 'グローバルセッションマップ',
    activeKey: '進行中の時間帯', inactiveKey: '時間帯外', crypto: '暗号資産 · 24時間365日',
    note: '平日の市場活動の目安であり、取引所の営業時間や祝日カレンダーではありません。暗号資産は常時取引可能です。現地時間は夏時間に自動対応します。',
    overlapNote: '2地域の活動時間帯が重なっています。', pause: 'マップの動きを停止', resume: 'マップの動きを再開',
    cities: { Tokyo: '東京', 'Hong Kong': '香港', Singapore: 'シンガポール', London: 'ロンドン', Frankfurt: 'フランクフルト', Zürich: 'チューリッヒ', 'New York': 'ニューヨーク' },
  },
  ko: {
    eyebrow: '글로벌 거래 세션', title: '시장은 잠들지 않습니다.', titleEnd: '중심이 이동할 뿐입니다.',
    description: '암호화폐는 24시간 거래됩니다. 글로벌 시장 활동은 아시아, 유럽, 미국을 따라 이동합니다.',
    current: '현재 세션', next: '다음 세션', overlap: '세션 중첩', nextOverlap: '다음 중첩',
    noActive: '세션 사이 시간', noOverlap: '예정된 중첩 없음', opens: '시작까지', closes: '종료까지', starts: '시작까지', ends: '종료까지',
    active: '활성', upcoming: '예정', closed: '종료', localTime: '현지 시간', anchorTime: '기준 도시 시간',
    window: '현지 세션 시간', elapsed: '세션 경과 시간', map: '글로벌 세션 지도',
    activeKey: '활성 시간대', inactiveKey: '시간대 외', crypto: '암호화폐 · 24시간 운영',
    note: '평일 시장 활동의 참고 시간대이며, 거래소 영업시간이나 공휴일 달력이 아닙니다. 암호화폐는 항상 거래됩니다. 현지 시간은 서머타임을 자동 반영합니다.',
    overlapNote: '두 지역의 활동 시간대가 겹칩니다.', pause: '지도 모션 일시 정지', resume: '지도 모션 재개',
    cities: { Tokyo: '도쿄', 'Hong Kong': '홍콩', Singapore: '싱가포르', London: '런던', Frankfurt: '프랑크푸르트', Zürich: '취리히', 'New York': '뉴욕' },
  },
};
