import React from 'react';
import { cascadeRisk, fundingSummary, longShort, oiStructure } from '../data/market';
import { Panel } from './ui/Panel';
import { Bar, Eyebrow, StatRow } from './ui/primitives';

export function OpenInterestStructure() { return <Panel title="Структура Open Interest" className="h-full"><div>{oiStructure.map(row=><StatRow key={row.label} label={row.label} value={row.value} tone={row.tone}/>)}</div><div className="mt-4 border-l-2 border-l-accent bg-accent-soft px-4 py-3"><p className="num text-[12px] font-medium text-ink">Цена ↑ / OI ↑</p><p className="mt-1 text-[11.5px] text-muted">Новый леверидж входит в рынок</p></div></Panel> }
export function FundingPressure(){return <Panel title="Давление funding" className="h-full"><div>{fundingSummary.map(row=><StatRow key={row.label} label={row.label} value={row.value} tone={row.tone}/>)}</div><div className="mt-4"><div className="flex items-baseline justify-between"><span className="text-[12px] text-muted">Положительный funding</span><span className="num text-[13px] font-medium text-ink">72%</span></div><div className="mt-2"><Bar value={72} color="bg-accent"/></div><p className="mt-2 text-[11px] text-faint">72% активов с положительным funding</p></div></Panel>}
export function CascadeRisk(){return <Panel title="Риск каскадных ликвидаций" className="h-full"><div className="flex items-end gap-2"><span className="num text-[34px] font-medium leading-none text-accent">{cascadeRisk.score}</span><span className="num pb-1 text-[12px] text-muted">/ 100 · {cascadeRisk.label}</span></div><div className="mt-5 space-y-3">{cascadeRisk.factors.map(factor=><div key={factor.label}><div className="flex items-baseline justify-between"><span className="text-[12px] text-muted">{factor.label}</span><span className="num text-[12px] font-medium text-ink">{factor.value}</span></div><div className="mt-1.5"><Bar value={factor.value} height="h-[5px]" color={factor.value>=80?'bg-neg':'bg-accent'}/></div></div>)}</div><p className="mt-5 border-t border-line pt-3 text-[11px] leading-[1.5] text-faint">{cascadeRisk.note}</p></Panel>}
export function LongShortRatio(){return <Panel title="Соотношение Long / Short" action={<Eyebrow>8ч интервал</Eyebrow>} source="Источник: CoinGlass · обновлено 14 сек. назад" className="h-full"><div className="flex items-baseline justify-between"><span className="num text-[15px] font-medium text-pos">{longShort.long}% Long</span><span className="num text-[15px] font-medium text-neg">{longShort.short}% Short</span></div><div className="mt-2.5 flex h-2 w-full overflow-hidden"><div className="bg-pos" style={{width:`${longShort.long}%`}}/><div className="bg-neg" style={{width:`${longShort.short}%`}}/></div><div className="mt-4">{longShort.rows.map(row=><StatRow key={row.label} label={row.label} value={row.value}/>)}<StatRow label={longShort.percentile.label} value={longShort.percentile.value} tone="warn" note={longShort.percentile.note}/></div></Panel>}
export function LeveragePressure(){return <Panel title="Давление левериджа" className="h-full"><div className="flex items-end gap-2"><span className="num text-[34px] font-medium leading-none text-accent">76</span><span className="num pb-1 text-[12px] text-muted">/ 100 · Высокое</span></div><div className="mt-5 space-y-3">{cascadeRisk.factors.slice(0,4).map(factor=><div key={factor.label}><div className="flex items-baseline justify-between"><span className="text-[12px] text-muted">{factor.label}</span><span className="num text-[12px] font-medium text-ink">{factor.value}</span></div><div className="mt-1.5"><Bar value={factor.value} height="h-[5px]" color={factor.value>=80?'bg-neg':'bg-accent'}/></div></div>)}</div><p className="mt-5 border-t border-line pt-3 text-[11px] text-faint">Измерение структуры рынка, не торговый сигнал.</p></Panel>}
