import React, { useState } from 'react';
import { currentPrice, exchangeLegend, liquidationBins, liquidationFilters, liquidationStats } from '../data/liquidations';
import { Eyebrow, Segmented } from './ui/primitives';

const zoneBand:Record<string,string>={gap:'bg-[#F7F7F8]',wall:'bg-accent-soft',critical:'bg-[#FBEEEC]',short:'bg-[#F7F7F8]',long:'bg-[#F7F7F8]'};
const zoneTone:Record<string,string>={gap:'text-faint',wall:'text-accent',critical:'text-neg',short:'text-muted',long:'text-muted'};
const CHART_HEIGHT=232;
function binTotal(bin:(typeof liquidationBins)[number]){return bin.binance+bin.bybit+bin.okx+bin.deribit+bin.bitget}
function curvePoints(values:number[]){const step=100/(values.length-1);return values.map((value,index)=>`${index*step},${100-value}`).join(' ')}

export function LiquidationMap(){
 const [asset,setAsset]=useState('BTC');const [range,setRange]=useState('±4%');const [timeframe,setTimeframe]=useState('12Ч');const [exchange,setExchange]=useState('Все биржи');
 const max=Math.max(...liquidationBins.map(binTotal));const priceIndex=liquidationBins.findIndex(bin=>bin.price>=currentPrice);const pricePosition=(priceIndex+.5)/liquidationBins.length*100;const zoneMarkers=liquidationBins.map((bin,index)=>({...bin,index})).filter(bin=>bin.zoneLabel);
 return <section className="border border-line bg-white"><header className="border-b border-line px-5 py-4"><h2 className="text-[15px] font-medium leading-5 text-ink">Карта ликвидаций и зоны ликвидности</h2><p className="mt-1.5 max-w-4xl text-[12px] leading-[1.5] text-muted">Локальная структура ликвидности вокруг текущей цены: распределение по биржам, кумулятивные Long / Short кривые и зоны концентрации плеча</p></header>
 <div className="flex flex-wrap items-center gap-3 border-b border-line px-5 py-3"><Segmented options={liquidationFilters.assets} value={asset} onChange={setAsset} size="sm" label="Актив"/><Segmented options={liquidationFilters.ranges} value={range} onChange={setRange} size="sm" label="Диапазон"/><Segmented options={liquidationFilters.windows} value={timeframe} onChange={setTimeframe} size="sm" label="Период"/><label className="sr-only" htmlFor="liq-exchange">Биржа</label><select id="liq-exchange" value={exchange} onChange={e=>setExchange(e.target.value)} className="h-[30px] border border-line bg-white px-2.5 text-[11px] text-muted outline-none transition-colors duration-150 ease-out hover:text-ink focus-visible:border-accent">{liquidationFilters.exchanges.map(option=><option key={option}>{option}</option>)}</select></div>
 <div className="grid grid-cols-2 border-b border-line lg:grid-cols-4">{liquidationStats.map((stat,index)=><div key={stat.label} className={`border-line px-5 py-4 ${index<2?'border-b lg:border-b-0':''} ${index===liquidationStats.length-1?'':'border-r'}`}><p className="text-[11px] text-muted">{stat.label}</p><p className="num mt-1.5 text-[14px] font-medium text-ink">{stat.value}</p></div>)}</div>
 <div className="px-5 pb-5 pt-4"><div className="relative mb-3 h-[34px]">{zoneMarkers.map((marker,order)=>{const left=(marker.index+.5)/liquidationBins.length*100;const top=order%2===0?0:16;return <div key={`${marker.price}-${marker.zoneLabel}`} className="absolute -translate-x-1/2 whitespace-nowrap" style={{left:`${left}%`,top}}><span className={`text-[9.5px] leading-none ${zoneTone[marker.zone??'gap']}`}>{marker.zoneLabel}</span></div>})}</div>
 <div className="relative border-b border-line" style={{height:CHART_HEIGHT}}>{[.25,.5,.75].map(line=><div key={line} className="absolute inset-x-0 border-t border-dashed border-line" style={{top:`${line*100}%`}} aria-hidden="true"/>)}<svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full" aria-hidden="true"><polyline points={curvePoints(liquidationBins.map(bin=>bin.cumLong))} fill="none" stroke="#0F9D58" strokeWidth="0.5" strokeDasharray="2 1.4" vectorEffect="non-scaling-stroke"/><polyline points={curvePoints(liquidationBins.map(bin=>bin.cumShort))} fill="none" stroke="#C8402E" strokeWidth="0.5" strokeDasharray="2 1.4" vectorEffect="non-scaling-stroke"/></svg>
 <div className="absolute inset-0 flex items-end">{liquidationBins.map(bin=>{const total=binTotal(bin);const height=total/max*(CHART_HEIGHT-12);return <div key={bin.price} className={`group relative flex h-full flex-1 items-end justify-center px-[3px] ${bin.zone?zoneBand[bin.zone]:''}`}><div className="relative w-full max-w-[26px]" style={{height}}>{exchangeLegend.map(source=>{const value=bin[source.key];return <div key={source.key} style={{height:`${value/total*100}%`,backgroundColor:source.color}}/>})}</div><div className="pointer-events-none absolute -top-1 left-1/2 z-20 w-40 -translate-x-1/2 -translate-y-full border border-ink-line bg-ink-soft px-3 py-2 text-[11px] leading-[1.5] text-ink-mute opacity-0 transition-opacity duration-150 ease-out group-hover:opacity-100"><span className="num block font-medium text-white">${bin.price.toLocaleString('en-US')}</span><span className="num">${(total*4.2).toFixed(1)}M ликвидаций</span>{bin.zoneLabel&&<span className="mt-1 block">{bin.zoneLabel}</span>}</div></div>})}</div><div className="absolute bottom-0 top-0 z-10 border-l border-dashed border-ink" style={{left:`${pricePosition}%`}} aria-hidden="true"/></div>
 <div className="num mt-2.5 flex justify-between text-[10px] text-faint">{[65683,66608,67508,68432,69332,70257,71157].map(price=><span key={price}>${price.toLocaleString('en-US')}</span>)}</div><p className="num mt-3 text-[11px] text-muted">Текущая цена: <span className="font-medium text-ink">$68,420</span></p>
 <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-line pt-4">{exchangeLegend.map(source=><span key={source.key} className="flex items-center gap-2 text-[11px] text-muted"><span className="h-[9px] w-[9px]" style={{backgroundColor:source.color}} aria-hidden="true"/>{source.label}</span>)}<span className="flex items-center gap-2 text-[11px] text-muted"><span className="h-0 w-4 border-t border-dashed border-pos" aria-hidden="true"/>Кумулятивные Long</span><span className="flex items-center gap-2 text-[11px] text-muted"><span className="h-0 w-4 border-t border-dashed border-neg" aria-hidden="true"/>Кумулятивные Short</span><span className="ml-auto"><Eyebrow>Окно {timeframe} · {range}</Eyebrow></span></div></div></section>
}
