import React,{useState} from 'react';
import {anomalies,correlation,fearGreed,movers,sectors} from '../data/flows';
import {Panel} from './ui/Panel';
import {Bar,Segmented,StatRow} from './ui/primitives';
import {changeTone,toneClass} from '../utils/tone';
export function CorrelationMatrix(){const[range,setRange]=useState('30Д');return <Panel title="Корреляция рынка" action={<Segmented options={correlation.ranges} value={range} onChange={setRange} size="sm" label="Период корреляции"/>} className="h-full"><div className="overflow-x-auto"><table className="w-full min-w-[440px] border-collapse text-left"><thead><tr><th scope="col" className="w-20 pb-2 text-left"/>{correlation.assets.map(asset=><th key={asset} scope="col" className="eyebrow pb-2 text-center text-faint">{asset}</th>)}</tr></thead><tbody>{correlation.matrix.map((row,rowIndex)=><tr key={correlation.assets[rowIndex]}><th scope="row" className="py-1 pr-3 text-left text-[11px] font-medium text-muted">{correlation.assets[rowIndex]}</th>{row.map((value,columnIndex)=><td key={columnIndex} className="p-[2px]"><div className="num flex h-8 items-center justify-center text-[11px] font-medium" style={{backgroundColor:`rgba(192, 138, 24, ${(value*.9).toFixed(2)})`,color:value>.62?'#FFFFFF':'#0B0C0E'}}>{value.toFixed(2)}</div></td>)}</tr>)}</tbody></table></div></Panel>}
export function FearGreed(){return <Panel title="Индекс страха и жадности" source="Источник: Alternative.me · обновлено 42 сек. назад" className="h-full"><div className="flex items-end gap-3"><span className="num text-[34px] font-medium leading-none text-accent">{fearGreed.score}</span><span className="pb-1 text-[13px] text-muted">{fearGreed.label}</span></div><div className="mt-4"><Bar value={fearGreed.score} color="bg-accent"/><div className="mt-2 flex justify-between text-[10px] text-faint"><span>Страх</span><span>Нейтрально</span><span>Жадность</span></div></div><div className="mt-4">{fearGreed.rows.map(row=><StatRow key={row.label} label={row.label} value={row.value}/>)}</div></Panel>}
export function Sectors(){return <Panel title="Сектора рынка" source="Источник: CoinGecko · обновлено 42 сек. назад" dense className="h-full"><div className="overflow-x-auto"><table className="w-full min-w-[520px] border-collapse text-left"><thead><tr className="border-b border-line">{['Сектор','24ч','7д','Капитализация','Объём'].map(head=><th key={head} scope="col" className="eyebrow px-5 py-2.5 text-faint">{head}</th>)}</tr></thead><tbody>{sectors.map(row=><tr key={row.sector} className="border-b border-line/70 transition-colors duration-150 ease-out last:border-b-0 hover:bg-[#FAFAFB]"><td className="px-5 py-2.5 text-[12.5px] font-medium text-ink">{row.sector}</td><td className={`num px-5 py-2.5 text-[12px] ${toneClass(changeTone(row.d1))}`}>{row.d1}</td><td className={`num px-5 py-2.5 text-[12px] ${toneClass(changeTone(row.d7))}`}>{row.d7}</td><td className="num px-5 py-2.5 text-[12px] text-ink">{row.cap}</td><td className="num px-5 py-2.5 text-[12px] text-muted">{row.volume}</td></tr>)}</tbody></table></div></Panel>}
export function Movers(){return <Panel title="Движение рынка" source="Источник: CoinGecko · обновлено 42 сек. назад" dense className="h-full"><div className="divide-y divide-line">{movers.map(item=><div key={item.asset} className="flex items-center justify-between gap-4 px-5 py-3.5"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center border border-line text-[10px] font-semibold text-muted">{item.asset.slice(0,1)}</span><div><p className="text-[12.5px] font-medium text-ink">{item.asset}</p><p className="num text-[11px] text-faint">{item.price}</p></div></div><div className="text-right"><p className={`num text-[13px] font-medium ${toneClass(item.tone)}`}>{item.change}</p><p className="num text-[11px] text-faint">{item.volume}</p></div></div>)}</div></Panel>}
const severityTone:Record<string,string>={Высокая:'text-neg',Средняя:'text-accent',Низкая:'text-faint'};
export function Anomalies(){return <Panel title="Аномалии рынка" dense className="h-full"><div className="divide-y divide-line">{anomalies.map(item=><article key={`${item.time}-${item.title}`} className="flex gap-4 px-5 py-3.5"><span className="num w-10 shrink-0 pt-[2px] text-[11px] text-faint">{item.time}</span><div className="min-w-0 flex-1"><p className="text-[12.5px] font-medium text-ink">{item.title} <span className="text-[11px] font-normal text-faint">{item.asset}</span></p><p className="num mt-1 text-[11.5px] leading-4 text-muted">{item.detail}</p></div><span className={`shrink-0 text-[11px] ${severityTone[item.severity]}`}>{item.severity}</span></article>)}</div></Panel>}
