import React,{useState} from 'react';
import {futuresBasis,marketBreadth,marketStructure,volatility} from '../data/market';
import {Panel} from './ui/Panel';
import {Bar,Segmented,StatRow} from './ui/primitives';
import {changeTone} from '../utils/tone';
export function MarketStructurePanel(){return <Panel title="Структура рынка" source="Источник: CoinGecko · обновлено 14 сек. назад" className="h-full"><div>{marketStructure.map(row=><StatRow key={row.label} label={row.label} value={row.value} tone={row.tone}/>)}</div></Panel>}
export function Volatility(){return <Panel title="Волатильность" className="h-full"><div className="flex items-end gap-2"><span className="num text-[26px] font-medium leading-none text-ink">{volatility.headline}</span></div><p className="mt-2 text-[11px] text-faint">{volatility.caption}</p><div className="mt-4">{volatility.rows.map(row=><StatRow key={row.label} label={row.label} value={row.value}/>)}<StatRow label={volatility.percentile.label} value={volatility.percentile.value} tone="warn" note={volatility.percentile.note}/></div></Panel>}
export function FuturesBasis(){const[tab,setTab]=useState('Perpetual');return <Panel title="Базис фьючерсов" dense className="h-full"><div className="border-b border-line px-5 py-3"><Segmented options={futuresBasis.tabs} value={tab} onChange={setTab} size="sm" label="Тип контракта"/></div><div className="px-5 py-4">{futuresBasis.rows.map(row=><StatRow key={row.label} label={row.label} value={row.value} tone={changeTone(row.value)}/>)}<StatRow label={futuresBasis.state.label} value={futuresBasis.state.value} tone="warn"/></div></Panel>}
export function MarketBreadth(){return <Panel title="Ширина рынка" className="h-full"><p className="num text-[26px] font-medium leading-none text-pos">{marketBreadth.headline}</p><div className="mt-4"><Bar value={68} color="bg-pos"/></div><div className="mt-4">{marketBreadth.rows.map(row=><StatRow key={row.label} label={row.label} value={row.value}/>)}</div></Panel>}
export function LargeLiquidationsTable({rows}:{rows:{time:string;asset:string;side:'Long'|'Short';price:string;volume:string;exchange:string;}[]}){return <Panel title="Крупные ликвидации" dense className="h-full"><div className="overflow-x-auto"><table className="w-full min-w-[520px] border-collapse text-left"><thead><tr className="border-b border-line">{['Время','Актив','Сторона','Цена','Объём','Биржа'].map(head=><th key={head} scope="col" className="eyebrow px-5 py-2.5 text-faint">{head}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.time} className="border-b border-line/70 transition-colors duration-150 ease-out hover:bg-[#FAFAFB] last:border-b-0"><td className="num px-5 py-2.5 text-[12px] text-muted">{row.time}</td><td className="px-5 py-2.5 text-[12px] font-medium text-ink">{row.asset}</td><td className={`px-5 py-2.5 text-[12px] ${row.side==='Long'?'text-pos':'text-neg'}`}>{row.side}</td><td className="num px-5 py-2.5 text-[12px] text-ink">{row.price}</td><td className="num px-5 py-2.5 text-[12px] font-medium text-ink">{row.volume}</td><td className="px-5 py-2.5 text-[12px] text-muted">{row.exchange}</td></tr>)}</tbody></table></div></Panel>}
