import { useEffect, useRef, useState } from 'react';
import { createChart, CandlestickSeries, HistogramSeries, LineSeries, ColorType, CrosshairMode, type IChartApi, type ISeriesApi, type IPriceLine, type Time } from 'lightweight-charts';
import { computeSMA,computeEMA,computeRSI,computeMACD,computeBollingerBands } from '../../../lib/indicators';
import TradeMarkers from './TradeMarkerRail';
import type { Candle,Fill } from './types';
type Props={id:string;candles:Candle[];currency:string;interval:string;entry:string|null;fills:Fill[];error:string;loading:boolean;older:()=>void};
export default function GlobalChart({id,candles,currency,interval,entry,fills,error,loading,older}:Props){
  const host=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<'Candlestick'>|null>(null),volume=useRef<ISeriesApi<'Histogram'>|null>(null),lines=useRef<ISeriesApi<'Line'>[]>([]),hist=useRef<ISeriesApi<'Histogram'>|null>(null),priceLine=useRef<IPriceLine|null>(null),framed=useRef('');
  const [chartApi,setChartApi]=useState<IChartApi|null>(null);
  const [indicator,setIndicator]=useState('MA'),[hover,setHover]=useState<Candle|null>(null);const rows=useRef(candles);rows.current=candles;
  useEffect(()=>{if(!host.current)return;const c=createChart(host.current,{autoSize:true,layout:{background:{type:ColorType.Solid,color:'#0e1118'},textColor:'#959dac',fontFamily:'Inter,Arial,sans-serif'},grid:{vertLines:{color:'#171d28'},horzLines:{color:'#171d28'}},crosshair:{mode:CrosshairMode.Normal},timeScale:{timeVisible:true,secondsVisible:false,borderColor:'#242c39',rightOffset:10},rightPriceScale:{borderColor:'#242c39'},localization:{locale:'ru-RU'}});chart.current=c;setChartApi(c);
    series.current=c.addSeries(CandlestickSeries,{upColor:'#21b58b',downColor:'#ed596d',borderVisible:false,wickUpColor:'#21b58b',wickDownColor:'#ed596d',priceFormat:{type:'price',precision:2,minMove:.01}});volume.current=c.addSeries(HistogramSeries,{priceScaleId:'volume',priceFormat:{type:'volume'},lastValueVisible:false,priceLineVisible:false});volume.current.priceScale().applyOptions({scaleMargins:{top:.82,bottom:0}});
    lines.current=[0,1,2].map((_,i)=>c.addSeries(LineSeries,{color:['#f0bf4c','#778bff','#da70b5'][i],lineWidth:1,lastValueVisible:false,priceLineVisible:false}));hist.current=c.addSeries(HistogramSeries,{priceScaleId:'osc',lastValueVisible:false,priceLineVisible:false});c.subscribeCrosshairMove(p=>setHover(rows.current.find(c=>c.time===p.time)||null));return()=>{c.remove();chart.current=null;series.current=null;priceLine.current=null;framed.current='';};},[]);
  useEffect(()=>{if(!series.current||!chart.current)return;series.current.setData(candles.map(c=>({...c,time:c.time as Time})));volume.current?.setData(candles.map(c=>({time:c.time as Time,value:c.volume,color:c.close>=c.open?'#21b58b45':'#ed596d45'})));
    if(candles.length&&framed.current!==id+interval){chart.current.timeScale().fitContent();framed.current=id+interval;}
    if(priceLine.current){series.current.removePriceLine(priceLine.current);priceLine.current=null;}if(entry&&Number(entry)>0)priceLine.current=series.current.createPriceLine({price:Number(entry),color:'#edc35a',lineWidth:1,lineStyle:2,title:'Средняя цена входа',axisLabelVisible:true});
    const osc=indicator==='RSI'||indicator==='MACD';const datasets=indicator==='MA'?[computeSMA(candles,20)]:indicator==='EMA'?[computeEMA(candles,20)]:indicator==='RSI'?[computeRSI(candles)]:indicator==='BB'?Object.values(computeBollingerBands(candles)):indicator==='MACD'?(()=>{const m=computeMACD(candles,12,26,9,{warmupFromValidMacd:true});hist.current?.setData(m.histogram.map(p=>({...p,time:p.time as Time})));return [m.macd,m.signal];})():[];
    if(indicator!=='MACD')hist.current?.setData([]);lines.current.forEach((l,i)=>{l.applyOptions({priceScaleId:osc?'osc':'right'});l.setData((datasets[i]||[]).map(p=>({...p,time:p.time as Time})));});chart.current.priceScale('right').applyOptions({scaleMargins:{top:.07,bottom:osc?.36:.22}});hist.current?.priceScale().applyOptions({scaleMargins:{top:.72,bottom:.04}});
  },[candles,id,interval,entry,fills,indicator]);
  const shown=hover||candles[candles.length-1];return <div className="vxg-chart"><div className="vxg-chart-tools"><select aria-label="Индикатор" value={indicator} onChange={e=>setIndicator(e.target.value)}>{['Нет','MA','EMA','RSI','MACD','BB'].map(x=><option key={x}>{x}</option>)}</select><button onClick={older} disabled={loading}>Ранее</button><button onClick={()=>chart.current?.timeScale().fitContent()}>Масштаб</button><span>VOLTEX · {currency}</span></div><div className="vxg-ohlc">{shown?<>О {shown.open.toFixed(2)} · В {shown.high.toFixed(2)} · Н {shown.low.toFixed(2)} · З {shown.close.toFixed(2)} · V {shown.volume.toLocaleString('ru-RU')}</>:'Свечи не получены'}</div><TradeMarkers chart={chartApi} id={id} interval={interval} candles={candles} fills={fills}/><div className="vxg-plot" ref={host}/>{!candles.length&&<div className="vxg-chart-overlay">{loading?'Загрузка рыночных свечей…':error||'Нет рыночных свечей'}</div>}{candles.length>0&&error&&<div className="vxg-chart-warning">{error} · Показана последняя полученная история</div>}</div>;
}
