import { useCallback,useEffect,useRef,useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import BigNumber from 'bignumber.js';
import { Nav } from '../../../components/Nav';
import GlobalChart from './GlobalChart';
import { DEFAULT_STOCKS_INSTRUMENT } from '../../../lib/stocksIdentity';
import { StockRequestError, globalStockErrorText as errorText } from '../stockRequestError';
import { quoteAge } from './tradeMarkers';
import type { Asset,Candle,Currency,Position,State } from './types';
import './globalStocks.css';
const API='/__stocks_global/';
const fmt=(v:string|number|null|undefined,d=6)=>v==null?'—':new BigNumber(v).toFixed(d).replace(/\.?0+$/,'')||'0';
const valid=(s:string)=>/^\d+(\.\d{1,8})?$/.test(s)&&new BigNumber(s).gt(0);
const orderLabel=(s:string)=>({OPEN:'Открыт',PARTIAL:'Частично исполнен',FILLED:'Исполнен',CANCELLED:'Отменён',PARTIAL_CANCELLED:'Исполнен частично, остаток отменён'}[s]||s);
const PENDING='voltex.stocks.global.pending.v2';
function Logo({asset}:{asset:Asset}){const [failed,setFailed]=useState(false);return <span className="vxg-logo">{asset.domain&&!failed?<img src={`https://${asset.domain}/favicon.ico`} alt={`Логотип ${asset.name}`} onError={()=>setFailed(true)}/>:<span title="Логотип недоступен">{asset.ticker.slice(0,2)}</span>}</span>;}
export default function GlobalStocks(){
  const [now,setNow]=useState(Date.now),[keyboard,setKeyboard]=useState(false);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{
    const viewport=window.visualViewport;
    const reveal=()=>{
      const field=document.activeElement;
      const editing=field instanceof HTMLInputElement&&!!field.closest('.vxg-ticket');
      setKeyboard(!!editing&&!!viewport&&window.innerHeight-viewport.height>160);
      if(editing&&window.innerWidth<=800) field.scrollIntoView({block:'nearest',behavior:'smooth'});
    };
    viewport?.addEventListener('resize',reveal);document.addEventListener('focusin',reveal);document.addEventListener('focusout',reveal);
    return()=>{viewport?.removeEventListener('resize',reveal);document.removeEventListener('focusin',reveal);document.removeEventListener('focusout',reveal);};
  },[]);
  const {instrumentId}=useParams(),navigate=useNavigate();const id=instrumentId?.includes(':')&&!instrumentId.startsWith('XNGS:')?instrumentId:DEFAULT_STOCKS_INSTRUMENT;
  const [state,setState]=useState<State|null>(null),[connected,setConnected]=useState(false),[currency,setCurrency]=useState<Currency>('USDT'),[region,setRegion]=useState(id.startsWith('MOEX:')?'RU':'US'),[search,setSearch]=useState(''),[favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('voltex.stocks.global.favorites')||'[]');}catch{return [];}});
  const [menu,setMenu]=useState(false),[view,setView]=useState('chart'),[accountTab,setAccountTab]=useState('positions'),[side,setSide]=useState<'BUY'|'SELL'>('BUY'),[type,setType]=useState<'MARKET'|'LIMIT'>('MARKET'),[quantity,setQuantity]=useState(''),[limit,setLimit]=useState(''),[interval,setIntervalValue]=useState(id.startsWith('MOEX:')?'1m':'15m'),[candles,setCandles]=useState<Candle[]>([]),[chartError,setChartError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[balances,setBalances]=useState({USDT:'10000',USDC:'10000'});
  const token=useRef(''),gate=useRef(false),selected=useRef(id),historyGeneration=useRef(0);selected.current=id;
  const accept=useCallback((s:State)=>{if(s.token)token.current=s.token;setState(old=>!old||s.revision>=old.revision?s:old);},[]);
  const poll=useCallback(async()=>{if(document.hidden)return;try{const r=await fetch(API+'state?id='+encodeURIComponent(id),{credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error();const s=await r.json();if(s.schema!==2)throw Error();accept(s);setConnected(true);}catch{setConnected(false);}},[id,accept]);
  useEffect(()=>{void poll();const timer=window.setInterval(()=>void poll(),3000);const visible=()=>{if(!document.hidden)void poll();};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[poll]);
  const act=async(path:string,body:unknown)=>{if(gate.current)return null;gate.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch(API+path,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json','X-Stocks-Token':token.current},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const s=await r.json();if(!r.ok)throw new StockRequestError(s.error);accept(s);return s;}catch(e){setError(errorText(e instanceof StockRequestError?e.code:'LOCAL_SERVICE_ERROR'));return null;}finally{gate.current=false;setBusy(false);}};
  const asset=state?.catalogue.find(a=>a.id===id),q=state?.quotes[id],price=type==='LIMIT'?limit:q?.prices[currency]?.[side==='BUY'?'buy':'sell']||'',ready=connected&&q?.status[currency]==='READY'&&now-q.receivedAt<30000&&now-q.timestamp<((asset?.delaySeconds||0)+60)*1000;
  const positions=Object.values(state?.positions||{}).filter(p=>Number(p.quantity)>0),open=state?.orders.filter(o=>['OPEN','PARTIAL'].includes(o.status))||[],position=state?.positions[id+'|'+currency],available=side==='BUY'?state?.wallets[currency].available:position?.available||'0';
  const total=valid(price)&&valid(quantity)?new BigNumber(price).times(quantity).toFixed(8,side==='BUY'?BigNumber.ROUND_CEIL:BigNumber.ROUND_FLOOR):null;
  const admission=state?.errors[id]||(q?.status[currency]&&q.status[currency]!=='READY'?q.status[currency]:'');
  const canOrder=connected&&!busy&&valid(quantity)&&valid(price)&&(type==='LIMIT'||ready)&&!!state&&(side==='BUY'?new BigNumber(total||0).lte(available||0):new BigNumber(quantity).lte(available||0));
  const history=useCallback(async(before?:number)=>{if(document.hidden)return;const generation=historyGeneration.current;setLoading(true);try{const r=await fetch(API+`history?id=${encodeURIComponent(id)}&interval=${interval}${before?'&before='+before:''}`,{credentials:'omit',signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok)throw new StockRequestError(j.error);if(selected.current!==id||generation!==historyGeneration.current)return;setCandles(old=>[...new Map([...old,...j.candles].map((c:Candle)=>[c.time,c])).values()].sort((a,b)=>a.time-b.time).slice(-1500));setChartError('');}catch(e){if(selected.current===id&&generation===historyGeneration.current)setChartError(errorText(e instanceof StockRequestError?e.code:'SOURCE_UNAVAILABLE'));}finally{if(generation===historyGeneration.current)setLoading(false);}},[id,interval]);
  useEffect(()=>{historyGeneration.current++;setCandles([]);setChartError('');void history();const timer=window.setInterval(()=>void history(),15000);const visible=()=>{if(!document.hidden)void history();};document.addEventListener('visibilitychange',visible);return()=>{historyGeneration.current++;clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[history]);
  const choose=(a:Asset)=>{setMenu(false);setQuantity('');setLimit('');setMessage('');setError('');setIntervalValue(a.timeframes.includes(interval)?interval:a.timeframes[0]);navigate('/stocks/'+encodeURIComponent(a.id));};
  const submitOrder=async()=>{const body={instrumentId:id,currency,side,type,quantity:new BigNumber(quantity).toFixed(8),...(type==='LIMIT'?{limitPrice:new BigNumber(limit).toFixed(8)}:{})};const signature=JSON.stringify(body);let pending;try{pending=JSON.parse(sessionStorage.getItem(PENDING)||'null');}catch{}if(pending?.signature!==signature)pending={id:crypto.randomUUID(),signature};sessionStorage.setItem(PENDING,JSON.stringify(pending));const result=await act('orders',{...body,id:pending.id});if(result){sessionStorage.removeItem(PENDING);setMessage(`${orderLabel(result.result.status)} · ${fmt(result.result.filled)} ${asset?.asset}`);setQuantity('');setAccountTab(result.result.filled!=='0.00000000'?'positions':'orders');}};
  const prepareSell=(p:Position,half:boolean)=>{const a=state?.catalogue.find(a=>a.id===p.instrumentId);if(a)choose(a);setCurrency(p.currency);setSide('SELL');setType('MARKET');setQuantity(new BigNumber(p.available).div(half?2:1).toFixed(8,BigNumber.ROUND_DOWN));setView('trade');};
  const toggleFavorite=(assetId:string)=>setFavorites(old=>{const n=old.includes(assetId)?old.filter(x=>x!==assetId):[...old,assetId];localStorage.setItem('voltex.stocks.global.favorites',JSON.stringify(n));return n;});
  const filtered=state?.catalogue.filter(a=>(region==='FAV'?favorites.includes(a.id):a.region===region)&&`${a.ticker} ${a.asset} ${a.name} ${a.provider}`.toLowerCase().includes(search.toLowerCase()))||[];
  return <div className={`vxg-page ${keyboard?'vxg-keyboard-open':''}`}><Nav active="/stocks" hideTicker readProfile={false}/><main className={`vxg-terminal vxg-view-${view}`}>
    <aside className={`vxg-roster ${menu?'vxg-open':''}`}><div className="vxg-roster-head"><strong>Акции</strong><button className="vxg-mobile" onClick={()=>setMenu(false)}>Закрыть</button></div><div className="vxg-categories">{[['US','США'],['RU','Россия'],['FAV','Избранное']].map(([v,label])=><button key={v} className={region===v?'selected':''} onClick={()=>setRegion(v)}>{label}</button>)}</div><input aria-label="Поиск компании или токена" placeholder="Компания, тикер, источник" value={search} onChange={e=>setSearch(e.target.value)}/><div className="vxg-assets">{filtered.map(a=><div key={a.id} className={a.id===id?'selected':''}><button aria-label={`Избранное ${a.asset} ${a.provider}`} onClick={()=>toggleFavorite(a.id)}>{favorites.includes(a.id)?'★':'☆'}</button><button className="vxg-asset" onClick={()=>choose(a)}><Logo asset={a}/><span><strong>{a.asset}</strong><small>{a.name}</small><em>{a.provider.toUpperCase()} · {a.kind==='token'?'Токен':'Акция MOEX'}</em></span><span>{fmt((state?.quotes[a.id]?.timestamp??0)>(a.display?.timestamp??0)?state?.quotes[a.id]?.last:a.display?.price,2)}<small>{a.currency}</small><small className="vxg-quote-age">{quoteAge(Math.max(state?.quotes[a.id]?.timestamp||0,a.display?.timestamp||0),now)}</small></span></button></div>)}</div><footer>Котировки из API источников<br/>Ордера остаются в VOLTEX</footer></aside>
    <section className="vxg-center"><header className="vxg-market-head"><button className="vxg-active-asset" onClick={()=>setMenu(!menu)}>{asset&&<Logo key={id} asset={asset}/>}<span><strong>{asset?.asset||'STOCKS'} <small>⌄</small></strong><small>{asset?.name||'Загрузка каталога'}</small></span></button><div className="vxg-last"><strong>{fmt(q?.last,2)}</strong><small>{asset?.currency} · {asset?.provider.toUpperCase()}</small><small className={ready?'vxg-quote-age':'vxg-quote-age stale'}>{quoteAge(q?.timestamp,now)}{asset?.delaySeconds?` · задержка ${asset.delaySeconds/60} мин`:!ready&&q?' · нет свежей цены':''}</small></div><div className={Number(q?.change24h)>=0?'up':'down'}>{q?.change24h==null?'—':`${q.change24h.toFixed(2)}%`}<small>За 24 часа</small></div><div className="vxg-volume">{fmt(q?.volume,2)}<small>Объём · {asset?.asset}</small></div></header>
      <div className="vxg-mobile-tabs"><button className={view==='chart'?'selected':''} onClick={()=>setView('chart')}>График</button><button className={view==='trade'?'selected':''} onClick={()=>setView('trade')}>Торговля</button><button className={view==='account'?'selected':''} onClick={()=>setView('account')}>Позиции / заявки</button></div>
      <div className="vxg-chart-section"><div className="vxg-timeframes">{(asset?.timeframes||['1m','5m','15m','30m','1h','4h','1D']).map(t=><button key={t} className={t===interval?'selected':''} onClick={()=>setIntervalValue(t)}>{t}</button>)}<span>{asset?.delaySeconds?`Задержка ${asset.delaySeconds/60} мин`:'Данные биржи'}</span></div><GlobalChart id={id} candles={candles} currency={asset?.currency||'USDT'} interval={interval} entry={position?.averageNative||null} fills={state?.fills||[]} error={chartError} loading={loading} older={()=>void history(candles[0]?candles[0].time*1000-1:undefined)}/></div>
      <section className="vxg-account"><div className="vxg-wallets">{(['USDT','USDC'] as const).map(c=><div key={c}><strong>{fmt(state?.wallets[c].cash)} <small>{c}</small></strong><small>В резерве {fmt(state?.wallets[c].reserved)} · PnL <b className={Number(state?.realized[c])>=0?'up':'down'}>{fmt(state?.realized[c])}</b></small></div>)}</div><div className="vxg-account-tabs">{[['positions',`Позиции (${positions.length})`],['orders',`Заявки (${open.length})`],['history','История'],['fills','Сделки']].map(([v,label])=><button key={v} className={accountTab===v?'selected':''} onClick={()=>setAccountTab(v)}>{label}</button>)}</div><div className="vxg-account-rows">
        {accountTab==='positions'&&(positions.length?positions.map(p=><article key={p.instrumentId+p.currency}><div><strong>{state?.catalogue.find(a=>a.id===p.instrumentId)?.asset} / {p.currency}</strong><small>{p.instrumentId} · {fmt(p.quantity)} ед.</small><small>Вход {fmt(p.average)} · Оценка {fmt(p.mark)}</small></div><div><b className={Number(p.unrealized)>=0?'up':'down'}>{fmt(p.unrealized)} {p.currency}</b><small>Нереализованный PnL</small><button disabled={busy||Number(p.available)<=0} onClick={()=>prepareSell(p,true)}>Продать 50%</button><button disabled={busy||Number(p.available)<=0} onClick={()=>prepareSell(p,false)}>Закрыть</button></div></article>):<p className="vxg-empty">Открытых позиций нет</p>)}
        {(accountTab==='orders'||accountTab==='history')&&((accountTab==='orders'?open:[...(state?.orders||[])].reverse()).map(o=><article key={o.id}><div><strong>{state?.catalogue.find(a=>a.id===o.instrumentId)?.asset} / {o.currency}</strong><small>{o.instrumentId} · {o.side} {o.type}</small><small>{fmt(o.filled)} / {fmt(o.quantity)} · {o.limitPrice?fmt(o.limitPrice):'Market'}</small></div><div><b>{orderLabel(o.status)}</b><small>{new Date(o.createdAt).toLocaleTimeString('ru-RU')}</small>{['OPEN','PARTIAL'].includes(o.status)&&<button disabled={busy} onClick={async()=>{if(await act('cancel',{id:o.id}))setMessage('Остаток заявки отменён');}}>Отменить</button>}</div></article>))}
        {accountTab==='orders'&&!open.length&&<p className="vxg-empty">Активных заявок нет</p>}
        {accountTab==='fills'&&[...(state?.fills||[])].reverse().map(f=><article key={f.id}><div><strong>{state?.catalogue.find(a=>a.id===f.instrumentId)?.asset} / {f.currency}</strong><small>{f.provider} · {fmt(f.quantity)} × {fmt(f.price)}</small><small>PnL {fmt(f.realized)} {f.currency} · Комиссия 0</small></div><div><b className={f.side==='BUY'?'up':'down'}>{f.side}</b><small>{new Date(f.timestamp).toLocaleTimeString('ru-RU')}</small></div></article>)}
      </div></section>
    </section>
    <aside className="vxg-ticket"><header><strong>Торговля</strong><span>{asset?.asset}/{currency}</span></header><p className="vxg-notice">Баланс и позиции — тестовые. Заявки не выходят на реальный рынок.</p><div className="vxg-currency">{(['USDT','USDC'] as const).map(c=><button className={currency===c?'selected':''} key={c} onClick={()=>setCurrency(c)}>{c}</button>)}</div><div className="vxg-sides"><button className={side==='BUY'?'buy selected':''} onClick={()=>setSide('BUY')}>Купить</button><button className={side==='SELL'?'sell selected':''} onClick={()=>setSide('SELL')}>Продать</button></div><div className="vxg-order-types">{(['MARKET','LIMIT'] as const).map(t=><button key={t} className={type===t?'selected':''} onClick={()=>{setType(t);if(t==='LIMIT'&&!limit)setLimit(q?.prices[currency]?.buy||'');}}>{t==='MARKET'?'Market':'Limit'}</button>)}</div>
      <div className="vxg-available">Доступно <b>{fmt(available)} {side==='BUY'?currency:asset?.asset}</b></div><form onSubmit={e=>{e.preventDefault();if(canOrder)void submitOrder();}}><label>Цена <span>{currency}</span><input aria-label="Цена" inputMode="decimal" value={price} disabled={type==='MARKET'} onChange={e=>setLimit(e.target.value.replace(',','.'))} placeholder="—"/></label><label>Количество <span>{asset?.kind==='token'?'токенов':'акций'}</span><input aria-label="Количество" inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value.replace(',','.'))} placeholder="0.00"/></label><label>Итого <span>{currency}</span><input aria-label="Итого" disabled value={fmt(total)} /></label><div className="vxg-available">Комиссия <b>0%</b></div><button className={`vxg-submit ${side==='BUY'?'buy':'sell'}`} disabled={!canOrder}>{side==='BUY'?'Купить':'Продать'} {asset?.asset}</button></form>
      {!connected&&<p role="alert" className="vxg-error">Нет связи с локальным сервисом</p>}{error&&<p role="alert" className="vxg-error">{error}</p>}{message&&<p role="status" className="vxg-success">{message}</p>}{admission&&<p className="vxg-error">{errorText(admission)}</p>}
      <div className="vxg-source"><strong>{asset?.kind==='token'?'Токенизированный инструмент':'Акция MOEX · расчётная пара'}</strong><p>{id}</p>{q&&<p>Котировка {new Date(q.timestamp).toLocaleTimeString('ru-RU')} · возраст {Math.max(0,Math.floor((Date.now()-q.timestamp)/1000))} с</p>}{asset?.delaySeconds? <p>Данные MOEX с задержкой не менее 15 минут</p>:null}{q?.fx[currency]?<p>{q.fx[currency]?.source}<br/>{q.fx[currency]?.policy}<br/>Курс: {fmt(q.fx[currency]?.rate,8)}</p>:currency==='USDT'&&asset?.currency==='USDT'?<p>Цена токена уже в USDT. Пересчёт через USD не применяется.</p>:<p>Исполнение требует проверенного курса.</p>}{asset?.kind==='token'&&<p>{q?.multiplier?<>Множитель {q.multiplier}{valid(quantity)&&<> · Эквивалент {fmt(new BigNumber(quantity).times(q.multiplier).toFixed(8))} акций</>}</>:'Множитель акций не подтверждён. Учёт ведётся в единицах токена.'}</p>}<button disabled={busy} onClick={()=>void act('refresh',{id})}>Обновить котировку</button></div>
      <details className="vxg-settings" onToggle={e=>{if(e.currentTarget.open&&state)setBalances({USDT:state.wallets.USDT.cash,USDC:state.wallets.USDC.cash});}}><summary>Тестовый кошелёк и правила</summary>{(['USDT','USDC'] as const).map(c=><label key={c}>Баланс {c}<input aria-label={`Тестовый баланс ${c}`} inputMode="decimal" value={balances[c]} onChange={e=>setBalances(b=>({...b,[c]:e.target.value.replace(',','.')}))}/></label>)}<button disabled={busy} onClick={async()=>{if(await act('balances',{id:crypto.randomUUID(),balances}))setMessage('Тестовый капитал обновлён; история сохранена');}}>Установить тестовый баланс</button><p>Модель: до 1 единицы на новое наблюдение цены, общий лимит для заявок. Market — IOC: неисполненный остаток отменяется. Limit — GTC: только новые наблюдения после подачи, без исторических high/low.</p><p>Котировки обновляются только пока открыта видимая вкладка. При скрытии исполнение приостанавливается.</p></details>
    </aside>
  </main></div>;
}
