import { useEffect,useRef,useState,type FormEvent } from 'react';
import { privateNumber,privateUtc } from '../../lib/privateTradingApi';
import { nativeDemoApi,type NativeDraft } from '../../lib/nativeDemoApi';
import { PrivateResultCardDialog } from './PrivateResultCardDialog';
import type { NativeDemoController } from './useNativeDemo';
import './nativeDemo.css';
export function NativeDemoSwitch({controller:c}:{controller:NativeDemoController}){return c.allowed?<div className="native-mode-switch" role="group" aria-label="Торговый счёт"><button type="button" aria-pressed={!c.requested} onClick={()=>c.toggle(false)}>Real</button><button type="button" aria-pressed={c.requested} onClick={()=>c.toggle(true)}>Demo</button></div>:null;}
export function NativeDemoTicket({controller:c,symbol,pickedPrice,pickedSequence}:{controller:NativeDemoController;symbol:string;pickedPrice?:string;pickedSequence?:number}){
  const[side,setSide]=useState<'LONG'|'SHORT'>('LONG'),[type,setType]=useState<'MARKET'|'LIMIT'>('MARKET'),[amount,setAmount]=useState('5000'),[leverage,setLeverage]=useState('10'),[price,setPrice]=useState('');
  const[tp,setTp]=useState(''),[sl,setSl]=useState(''),[point,setPoint]=useState<'OPEN'|'CLOSE'>('CLOSE');
  useEffect(()=>{if(pickedPrice){setPrice(pickedPrice);setType('LIMIT');}},[pickedPrice,pickedSequence]);
  const selected=c.candle&&c.candle.symbol===symbol.replace(/[^A-Z0-9]/gi,'').toUpperCase()?c.candle:null;
  async function submit(e:FormEvent){e.preventDefault();const candle=selected?{source:'BYBIT_LINEAR' as const,interval:selected.interval,openTime:selected.openTime,pricePoint:point}:undefined;
    const draft:NativeDraft=c.exitId?{kind:'CLOSE',positionId:c.exitId,...(candle?{candle}:{})}:{kind:'OPEN',symbol,side,type,margin:amount,leverage,...(type==='LIMIT'?{price}:{}),...(candle?{candle}:{}),protection:{takeProfit:tp||null,stopLoss:sl||null}};
    if(await c.run(draft)){c.setCandle(null);c.setExitId(null);}}
  if(!c.allowed)return <div className="native-demo-controls" role="status">{c.checked?'Приватный Demo недоступен для этого аккаунта.':'Проверка доступа…'}</div>;
  const state=c.state;
  return <div className="native-demo-controls">
    <header><b>Demo · Cross</b><span>USDT Perpetual</span></header>
    {state?.source==='PREVIEW_FIXTURE'&&<p className="native-preview-label">Тестовый баланс preview. Не ваш счёт.</p>}
    {c.error&&<p role="alert">{c.error}</p>}
    {!state?<p role="status">Загрузка демо-счёта…</p>:!state.initialized?<div className="native-demo-connect"><p>Доступно демо-средств: <b>{privateNumber(state.demoAvailable)} USDT</b></p><p>Весь переведённый демо-баланс — общее обеспечение Cross Margin. Реальные средства не используются.</p><p>Модель funding: Long −0.1%, Short +0.4% каждые 8 ч UTC. Это коэффициенты −0.001 / +0.004, не рыночный funding Bybit.</p><button type="button" disabled={c.busy||!state.demoAvailable} onClick={()=>void c.initialize()}>Использовать демо-средства</button></div>:<>
      <div className="native-balance"><span>Доступно</span><b>{privateNumber(state.account?.available)} USDT</b></div>
      <form onSubmit={submit}>
        <div className="native-side"><button type="button" className="positive" aria-pressed={side==='LONG'} onClick={()=>setSide('LONG')}>Long</button><button type="button" className="negative" aria-pressed={side==='SHORT'} onClick={()=>setSide('SHORT')}>Short</button></div>
        <div className="native-types"><button type="button" aria-pressed={type==='MARKET'} onClick={()=>setType('MARKET')}>Рыночный</button><button type="button" aria-pressed={type==='LIMIT'} onClick={()=>setType('LIMIT')}>Лимитный</button></div>
        <button type="button" className="native-history" disabled={c.busy} onClick={c.pickEntry}>Выбрать вход на графике</button>
        {selected&&<section className="native-candle"><b>{c.exitId?'Выбран выход':'Исторический вход'}</b><span>{privateUtc(selected.openTime)}</span><label>Цена свечи<select value={point} onChange={e=>setPoint(e.target.value as 'OPEN'|'CLOSE')}><option value="OPEN">Открытие</option><option value="CLOSE">Закрытие</option></select></label><button type="button" onClick={()=>{c.setCandle(null);c.setExitId(null);}}>Отменить выбор</button></section>}
        {type==='LIMIT'&&!c.exitId&&<label>Лимитная цена<input aria-label="Лимитная цена" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} required/></label>}
        {!c.exitId&&<><label>Маржа, USDT<input aria-label="Маржа, USDT" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Плечо<input aria-label="Плечо" inputMode="decimal" value={leverage} onChange={e=>setLeverage(e.target.value)} required/></label><details><summary>TP/SL</summary><label>Take Profit<input aria-label="Take Profit" inputMode="decimal" value={tp} onChange={e=>setTp(e.target.value)} placeholder="Не установлен"/></label><label>Stop Loss<input aria-label="Stop Loss" inputMode="decimal" value={sl} onChange={e=>setSl(e.target.value)} placeholder="Не установлен"/></label></details></>}
        <button type="submit" className={`native-submit ${side==='LONG'?'long':'short'}`} disabled={c.busy||(!!c.exitId&&!selected)}>{c.busy?'Сервер рассчитывает…':c.exitId?'Закрыть на выбранной свече':selected?'Открыть историческую сделку':`Открыть ${side==='LONG'?'Long':'Short'}`}</button>
      </form>
      <dl><dt>Обеспечение</dt><dd>{privateNumber(state.account?.equity)} USDT</dd><dt>Использовано</dt><dd>{privateNumber(state.account?.usedMargin)} USDT</dd><dt>Резерв ордеров</dt><dd>{privateNumber(state.account?.orderReserve)} USDT</dd></dl>
      <details className="native-model"><summary>Условия Demo</summary><p>Funding: Long −0.1%, Short +0.4% / 8 ч UTC. Фиксированная пользовательская модель.</p><p>История: предполагаемый путь Open → Low → High → Close. Историческое исполнение — симуляция, не сделка на Bybit. Общий капитал считается доступным с начала сценария.</p><p>Ликвидация оценивается по общему обеспечению и Mark Price. Не по марже отдельного ордера.</p></details>
    </>}
  </div>;
}
export function NativeDemoPanel({controller:c}:{controller:NativeDemoController}){
  const[tab,setTab]=useState<'positions'|'orders'|'history'|'fills'>('positions'),s=c.state;
  const prev=useRef(0);useEffect(()=>{if((s?.positions.length??0)>prev.current)setTab('positions');prev.current=s?.positions.length??0;},[s?.positions.length]);
  const rows=tab==='history'?s?.history:s?.positions;
  return <div className="native-demo-panel"><div className="bottom-tabs" role="tablist" aria-label="Демо-счёт">{([['positions','Позиции'],['orders','Ордера'],['history','История позиций'],['fills','Исполнения / Funding']] as const).map(([id,label])=><button key={id} type="button" className={`bottom-tab ${id===tab?'active':''}`} role="tab" aria-selected={id===tab} onClick={()=>setTab(id)}>{label}</button>)}<button type="button" className="bottom-tab" disabled={c.busy||!s?.initialized} onClick={()=>void c.run({kind:'REFRESH'})}>Обновить</button></div>
    {!s||!s.initialized?<p className="native-empty">{!s?'Данные счёта ещё не получены.':'Подключите существующие демо-средства в торговой панели.'}</p>:<div className="native-table-scroll">
      {(tab==='positions'||tab==='history')&&<table><thead><tr><th>Контракт</th><th>Количество</th><th>Цена Входа</th><th>{tab==='history'?'Цена выхода':'Рыночная цена'}</th><th>Маржа</th><th>P&amp;L / ROI</th><th>Funding</th><th>TP/SL</th><th>Закрыть</th></tr></thead><tbody>{rows?.map(p=><tr key={p.id} aria-selected={c.selectedId===p.id}><td><button type="button" onClick={()=>c.selectEntry(p)}><b>{p.symbol}</b></button><small className={p.side==='LONG'?'positive':'negative'}>{p.side} · Cross {p.leverage}×</small>{p.historical&&<small>Historical Test</small>}</td><td>{privateNumber(p.quantity,3)}</td><td>{privateNumber(p.entryPrice,2)}</td><td>{privateNumber(p.markPrice,2)}</td><td>{privateNumber(p.roiBasis)}</td><td><span className={Number(p.status==='OPEN'?p.unrealizedPnl:p.netPnl)<0?'negative':'positive'}>{privateNumber(p.status==='OPEN'?p.unrealizedPnl:p.netPnl)} USDT<br/>{privateNumber(p.roiPercent)}%</span><button type="button" aria-label={`Карточка ${p.symbol}`} onClick={()=>void c.showCard(p.id)}>↗</button></td><td>{privateNumber(p.fundingNet)}</td><td><button type="button" disabled={c.busy||p.status!=='OPEN'} onClick={()=>c.setDialog({kind:'protection',position:p})}>TP/SL</button><button type="button" disabled={c.busy||p.status!=='OPEN'} onClick={()=>c.setDialog({kind:'leverage',position:p})}>Плечо</button></td><td>{p.status==='OPEN'?<><button type="button" disabled={c.busy} onClick={()=>c.setDialog({kind:'close',position:p})}>Рыночный</button><button type="button" disabled={c.busy} onClick={()=>c.exitOnChart(p)}>На графике</button></>:p.status}</td></tr>)}{!rows?.length&&<tr><td colSpan={9}>Подтверждённых позиций нет</td></tr>}</tbody></table>}
      {tab==='orders'&&<table><thead><tr><th>Контракт</th><th>Направление</th><th>Тип</th><th>Цена</th><th>Количество</th><th>Исполнено</th><th>Статус</th><th/></tr></thead><tbody>{s.orders.map(o=><tr key={o.id}><td>{o.symbol}</td><td>{o.side}</td><td>{o.type}</td><td>{privateNumber(o.price)}</td><td>{privateNumber(o.quantity,3)}</td><td>{privateNumber(o.filled,3)}</td><td>{o.status}</td><td>{['OPEN','PARTIALLY_FILLED'].includes(o.status)&&<button type="button" disabled={c.busy} onClick={()=>void c.run({kind:'CANCEL',orderId:o.id})}>Отменить</button>}</td></tr>)}</tbody></table>}
      {tab==='fills'&&<table><thead><tr><th>Время UTC</th><th>Контракт</th><th>Операция</th><th>Цена</th><th>Количество</th><th>Комиссия</th><th>Изменение баланса</th></tr></thead><tbody>{[...s.events].reverse().map(e=><tr key={e.id}><td>{privateUtc(e.time)}</td><td>{e.symbol}</td><td>{e.kind}</td><td>{privateNumber(e.price)}</td><td>{privateNumber(e.quantity,3)}</td><td>{privateNumber(e.fee,6)}</td><td>{privateNumber(e.cashflow,6)}</td></tr>)}</tbody></table>}
    </div>}
    {s?.asOf&&<div className="native-asof">Серверный расчёт: {privateUtc(s.asOf)} · Ревизия {s.revision}</div>}
  </div>;
}
export function NativeDemoDialogs({controller:c}:{controller:NativeDemoController}){
  return <>{c.dialog&&<NativeAction key={c.dialog.kind+c.dialog.position.id} controller={c}/>} {c.card&&<PrivateResultCardDialog snapshot={c.card} loadSnapshot={nativeDemoApi.getCard} openHref={`/futures?demo=1&nativeCard=${encodeURIComponent(c.card.id)}`} onClose={()=>c.setCard(null)} onError={c.fail}/>}</>;
}
function NativeAction({controller:c}:{controller:NativeDemoController}){
  const d=c.dialog!,p=d.position,ref=useRef<HTMLDialogElement>(null),[qty,setQty]=useState(''),[tp,setTp]=useState(p.protection.takeProfit??''),[sl,setSl]=useState(p.protection.stopLoss??''),[leverage,setLeverage]=useState(p.leverage),[trigger,setTrigger]=useState<'MARK'|'LAST'>(p.protection.triggerBy);
  useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
  async function submit(e:FormEvent){e.preventDefault();let body:NativeDraft=d.kind==='close'?{kind:'CLOSE',positionId:p.id,...(qty?{quantity:qty}:{})}:d.kind==='leverage'?{kind:'LEVERAGE',positionId:p.id,leverage}:{kind:'PROTECTION',positionId:p.id,protection:{takeProfit:tp||null,stopLoss:sl||null,triggerBy:trigger,quantity:qty||null}};if(await c.run(body))c.setDialog(null);}
  return <dialog ref={ref} className="native-action-dialog" onCancel={()=>c.setDialog(null)}><form onSubmit={submit}><header><b>{p.symbol} · {d.kind==='protection'?'TP/SL':d.kind==='close'?'Закрытие позиции':'Плечо'}</b><button type="button" aria-label="Закрыть окно" onClick={()=>c.setDialog(null)}>×</button></header>
    {d.kind==='leverage'?<label>Плечо<input value={leverage} onChange={e=>setLeverage(e.target.value)} inputMode="decimal" required/></label>:<><label>Количество · пусто = вся позиция<input aria-label="Количество закрытия" value={qty} onChange={e=>setQty(e.target.value)} inputMode="decimal" placeholder={p.quantity}/></label>{d.kind==='protection'&&<><label>Take Profit<input aria-label="Цена TP" value={tp} onChange={e=>setTp(e.target.value)} inputMode="decimal"/></label><label>Stop Loss<input aria-label="Цена SL" value={sl} onChange={e=>setSl(e.target.value)} inputMode="decimal"/></label><label>Цена срабатывания<select value={trigger} onChange={e=>setTrigger(e.target.value as 'MARK'|'LAST')}><option value="MARK">Mark Price</option><option value="LAST">Last Price</option></select></label><p>Пустое поле удаляет соответствующий TP или SL.</p></>}</>}
    {c.error&&<p role="alert">{c.error}</p>}<button type="submit" disabled={c.busy}>{c.busy?'Выполняется…':'Подтвердить'}</button></form></dialog>;
}
