import { useEffect,useRef,useState } from 'react';
import { Image as ImageIcon,X } from 'lucide-react';
import { LiveMetric } from '../copy-trading-bolt/LiveMetric';
import { privateEffectiveSort,privatePositionPnl,privateNumber,privateUtc,type PrivatePosition,type PrivateState } from '../../lib/privateTradingApi';

export type PrivatePositionAction={kind:'close'|'protection'|'margin';position:PrivatePosition};
export function PrivatePositions({state,busy,onAction,onCard,onCancelOrder,onAdvance}:{state:PrivateState;busy:boolean;onAction:(action:PrivatePositionAction)=>void;onCard:(id:string)=>void;onCancelOrder:(id:string)=>void;onAdvance:(id:string)=>void}){
  const[tab,setTab]=useState<'positions'|'orders'|'orderHistory'|'history'|'scenarios'|'copy'>('positions');
  const verifiedScenarios=state.scenarios.filter(scenario=>scenario.verification==='VERIFIED');
  const positionRows=[...state.positions,...verifiedScenarios.filter(scenario=>scenario.status==='OPEN')];
  const historyRows=[...state.history,...verifiedScenarios.filter(scenario=>scenario.status!=='OPEN')];
  const count=useRef({positions:positionRows.length,history:historyRows.length});
  useEffect(()=>{
    if(positionRows.length>count.current.positions)setTab('positions');
    else if(historyRows.length>count.current.history)setTab('history');
    count.current={positions:positionRows.length,history:historyRows.length};
  },[positionRows.length,historyRows.length]);
  const activeOrders=state.orders.filter(order=>['OPEN','PARTIALLY_FILLED'].includes(order.status));
  const pnl=privatePositionPnl;
  const table=(rows:PrivatePosition[],active:boolean)=>rows.length?<table><thead><tr><th>Контракт</th><th>Количество</th><th>Номинал</th><th>Средний вход</th><th>Mark Price</th><th>Ликвидация</th><th>Маржа</th><th>Прибыль, USDT</th><th>ROI</th><th>TP / SL</th><th>Время UTC</th><th>Действия</th></tr></thead><tbody>{privateEffectiveSort(rows).map(position=><tr key={position.id}>
    <td><strong>{position.symbol}</strong>{position.dataStatus==='UNAVAILABLE'&&<small>Обновление котировки</small>}<small className={position.side==='LONG'?'positive':'negative'}>{position.side==='LONG'?'Long':'Short'} · {position.leverage}× · {position.mode==='HISTORICAL_REPLAY'?'По истории':'Изолированная'}</small>{position.verification&&position.verification!=='VERIFIED'&&<small>Не подтверждён</small>}</td>
    <td>{privateNumber(position.status==='OPEN'?position.quantity:position.initialQuantity??position.quantity,8)}</td><td>{privateNumber(position.dataStatus==='UNAVAILABLE'?null:position.notional)}</td><td>{privateNumber(position.entryPrice,6)}</td><td>{privateNumber(position.dataStatus==='UNAVAILABLE'?null:position.markPrice,6)}</td><td>{privateNumber(position.dataStatus==='UNAVAILABLE'?null:position.liquidationPrice,6)}</td><td>{privateNumber(position.allocatedMargin)}</td>
    <td className={pnl(position)!==null&&Number(pnl(position))<0?'negative':'positive'}><span className="private-pnl-card"><LiveMetric value={privateNumber(pnl(position))}/><button type="button" className="private-icon-button" disabled={busy||position.dataStatus==='UNAVAILABLE'||position.verification==='INCOMPLETE'||position.verification==='AMBIGUOUS'} aria-label={`Открыть карточку ${position.symbol}`} title="Карточка результата" onClick={()=>onCard(position.id)}><ImageIcon size={15}/></button></span><small>{position.mode==='DEMO_LIVE'&&position.status==='OPEN'?'Нереализованная':'Итого'}{active&&position.mode==='DEMO_LIVE'?` · Итого ${privateNumber(position.dataStatus==='UNAVAILABLE'?null:position.netPnl)} USDT`:''}</small></td>
    <td>{privateNumber(position.dataStatus==='UNAVAILABLE'?null:position.roiPercent)}%</td><td>{privateNumber(position.takeProfit,6)} / {privateNumber(position.stopLoss,6)}</td><td>{privateUtc(position.effectiveClosedAt||position.effectiveOpenedAt)}{position.mode==='HISTORICAL_REPLAY'&&<small>На: {privateUtc(position.asOf)}</small>}</td>
    <td>{active&&position.mode==='DEMO_LIVE'?<div className="private-table-actions"><button type="button" disabled={busy} onClick={()=>onAction({kind:'protection',position})}>TP/SL</button><button type="button" disabled={busy} onClick={()=>onAction({kind:'margin',position})}>Маржа</button><button type="button" disabled={busy} onClick={()=>onAction({kind:'close',position})}>Закрыть</button></div>:active&&position.mode==='HISTORICAL_REPLAY'?<button type="button" disabled={busy} onClick={()=>onAdvance(position.id)}>Обновить до сейчас</button>:<span>{position.status}</span>}</td>
  </tr>)}</tbody></table>:<div className="private-empty">{active?'Нет открытых позиций':'История пока пуста'}</div>;
  return <section className="private-bottom-panel"><div className="private-bottom-tabs" role="tablist" aria-label="Приватный торговый счёт">
    {([['positions',`Позиции (${positionRows.length})`],['orders',`Открытые ордера (${activeOrders.length})`],['orderHistory','История ордеров'],['history','История позиций'],['scenarios','Сценарии'],['copy','Приватный копитрейдинг']] as const).map(([id,label])=><button type="button" role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}
  </div><div className="private-table-scroll" role="tabpanel">
    {tab==='positions'&&table(positionRows,true)}{tab==='history'&&table(historyRows,false)}
    {tab==='copy'&&<><div className="private-copy-summary"><span>Реализованная прибыль <strong><LiveMetric value={`${privateNumber(state.wallet.realizedPnl)} USDT`}/></strong></span><span>Исторические сценарии учитываются отдельно.</span></div>{table(state.copyHistory,false)}</>}
    {(tab==='orders'||tab==='orderHistory')&&(()=>{const orders=tab==='orders'?activeOrders:(state.orderHistory??state.orders.filter(order=>!['OPEN','PARTIALLY_FILLED'].includes(order.status)));return orders.length?<table><thead><tr><th>Контракт</th><th>Направление</th><th>Тип</th><th>Цена</th><th>Количество</th><th>Исполнено</th><th>Остаток</th><th>Статус</th><th>Время UTC</th><th/></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td>{order.symbol}</td><td>{order.side}</td><td>{order.type}</td><td>{privateNumber(order.limitPrice,6)}</td><td>{privateNumber(order.quantity,8)}</td><td>{privateNumber(order.filledQuantity,8)}</td><td>{privateNumber(order.remainingQuantity,8)}</td><td>{order.status}</td><td>{privateUtc(order.effectiveAt||order.createdAt)}</td><td>{tab==='orders'&&<button type="button" disabled={busy} onClick={()=>onCancelOrder(order.id)}>Отменить остаток</button>}</td></tr>)}</tbody></table>:<div className="private-empty">{tab==='orders'?'Нет открытых ордеров':'История ордеров пока пуста'}</div>;})()}
    {tab==='scenarios'&&(state.scenarios.length?<table><thead><tr><th>Контракт</th><th>Вход UTC</th><th>Рассчитан до</th><th>Капитал, USDT</th><th>Средства, USDT</th><th>Прибыль, USDT</th><th>Результат</th><th>Проверка</th><th/></tr></thead><tbody>{state.scenarios.map(scenario=><tr key={scenario.id}><td>{scenario.symbol}</td><td>{privateUtc(scenario.effectiveOpenedAt)}</td><td>{privateUtc(scenario.asOf)}</td><td>{privateNumber(scenario.allocatedCapital)}</td><td>{privateNumber(scenario.verification==='VERIFIED'?scenario.scenarioEquity:null)}</td><td>{privateNumber(scenario.verification==='VERIFIED'?scenario.netPnl:null)}</td><td>{scenario.status}</td><td>{scenario.verification==='VERIFIED'?'Подтверждён':scenario.verification==='AMBIGUOUS'?'Неоднозначный':'Неполный'}</td><td>{scenario.status==='OPEN'&&<button type="button" disabled={busy} onClick={()=>onAdvance(scenario.id)}>Обновить до сейчас</button>}</td></tr>)}</tbody></table>:<div className="private-empty">Нет сохранённых сценариев</div>)}
  </div></section>;
}

export function PrivatePositionDialog({action,busy,error,onClose,onSubmit}:{action:PrivatePositionAction;busy:boolean;error?:string;onClose:()=>void;onSubmit:(body:{quantity?:string;takeProfit?:string|null;stopLoss?:string|null;marginDelta?:string})=>void}){
  const dialog=useRef<HTMLDialogElement>(null),[quantity,setQuantity]=useState(action.position.quantity),[margin,setMargin]=useState(''),[tp,setTp]=useState(action.position.takeProfit??''),[sl,setSl]=useState(action.position.stopLoss??'');
  useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
  const title=action.kind==='close'?'Закрытие позиции':action.kind==='margin'?'Изменить маржу':'Защита позиции';
  return <dialog ref={dialog} className="private-action-dialog" aria-label={title} onCancel={()=>{if(!busy)onClose();}}><header><strong>{title} · {action.position.symbol}</strong><button type="button" disabled={busy} aria-label="Закрыть" onClick={onClose}><X size={18}/></button></header><form onSubmit={event=>{event.preventDefault();onSubmit(action.kind==='close'?{quantity}:action.kind==='margin'?{marginDelta:margin}:{takeProfit:tp||null,stopLoss:sl||null});}}>
    {action.kind==='close'&&<><label>Количество для закрытия<input type="number" min="0.00000001" max={action.position.quantity} step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><p>Открыто: {privateNumber(action.position.quantity,8)}. Исполнение по доступной свежей ликвидности.</p></>}
    {action.kind==='margin'&&<><label>Изменение маржи, USDT<input type="number" step="any" value={margin} onChange={e=>setMargin(e.target.value)} required/></label><p>Положительная сумма добавляет маржу, отрицательная — снимает допустимый остаток.</p></>}
    {action.kind==='protection'&&<><label>Take-profit<input type="number" min="0.00000001" step="any" value={tp} onChange={e=>setTp(e.target.value)}/></label><label>Stop-loss<input type="number" min="0.00000001" step="any" value={sl} onChange={e=>setSl(e.target.value)}/></label><p>Пустое поле отменяет соответствующий уровень.</p></>}
    {error&&<p role="alert">{error}</p>}
    <button className="primary" disabled={busy}>{busy?'Сохранение…':'Подтвердить'}</button>
  </form></dialog>;
}
