import type React from 'react';
import {Clock3} from 'lucide-react';
type Asset = 'Обзор' | 'BTC' | 'ETH' | 'SOL' | 'XRP'
const data: Record<Exclude<Asset, 'Обзор'>, { price:string; change:string; oi:string; oiChange:string; funding:string; vol:string; basis:string; low:string; high:string; below:string; above:string }> = {
  BTC: { price:'$68,420', change:'+2.1%', oi:'$32.8B', oiChange:'+7.4%', funding:'+0.008%', vol:'48.2%', basis:'+0.82%', low:'$63,880', high:'$70,420', below:'-3.2%', above:'+5.5%' },
  ETH: { price:'$3,511', change:'+3.2%', oi:'$18.4B', oiChange:'+4.1%', funding:'+0.004%', vol:'44.8%', basis:'+0.61%', low:'$3,180', high:'$3,680', below:'-4.1%', above:'+4.8%' },
  SOL: { price:'$184.72', change:'-0.8%', oi:'$6.1B', oiChange:'+6.8%', funding:'+0.031%', vol:'62.4%', basis:'+1.24%', low:'$158.20', high:'$204.80', below:'-3.4%', above:'+6.2%' },
  XRP: { price:'$0.624', change:'+1.4%', oi:'$2.4B', oiChange:'+2.2%', funding:'-0.018%', vol:'51.7%', basis:'-0.24%', low:'$0.571', high:'$0.682', below:'-4.8%', above:'+9.3%' },
}
const funding = [['BTC','+0.008%','+0.006%','+0.010%','+0.021%','+0.034%'],['ETH','+0.004%','+0.002%','+0.001%','+0.008%','+0.016%'],['SOL','+0.031%','+0.011%','+0.018%','+0.029%','+0.051%'],['XRP','-0.018%','-0.004%','-0.008%','-0.011%','-0.019%'],['DOGE','+0.014%','+0.021%','+0.031%','+0.048%','+0.072%']]
const sectors = [['Layer 1','+2.84%','+7.12%','$1.24T','$48.7B'],['Layer 2','+1.96%','+6.42%','$32.6B','$2.9B'],['DeFi','+3.18%','+9.84%','$86.1B','$6.8B'],['AI','+4.92%','+12.30%','$41.8B','$4.2B'],['RWA','+0.74%','+3.11%','$58.4B','$1.7B']]
const movers = [['ONDO','$1.02','+18.42%','$842M'],['PEPE','$0.000012','+12.87%','$1.2B'],['TIA','$7.44','-8.21%','$381M']]
const leverageMetrics = [82, 74, 67, 81]
const leverageComposite = leverageMetrics.reduce((sum, value) => sum + value, 0) / leverageMetrics.length

function Section({ title, action, children, className = '' }: { title:string; action?:React.ReactNode; children:React.ReactNode; className?:string }) { return <section className={`surface ${className}`}><div className="section-heading"><h2>{title}</h2>{action}</div>{children}</section> }
function Fresh() {return <div className="data-freshness">Демонстрационный срез · не реальные рыночные данные</div>}
function Coin({ ticker }: { ticker:string }) { return <span className="coin"><span className={`coin-mark ${ticker.toLowerCase()}`}>{ticker[0]}</span><b>{ticker}</b></span> }
function Metric({ label, value, note = '', tone = '' }: { label:string; value:string; note?:string; tone?:string }) { return <div className="metric-row"><span>{label}</span><b className={tone}>{value}</b><small>{note}</small></div> }
function Chart({ oi = false }: { oi?:boolean }) { return <div className="chart-wrap"><div className="chart-y"><span>{oi ? '$70B' : '$2.80T'}</span><span>{oi ? '$65B' : '$2.74T'}</span><span>{oi ? '$60B' : '$2.68T'}</span><span>{oi ? '$55B' : '$2.62T'}</span></div><svg className="chart" viewBox="0 0 760 260" preserveAspectRatio="none" role="img" aria-label={oi ? 'Цена и открытый интерес' : 'Динамика рынка'}><g className="grid">{[30,80,130,180,230].map(y=><line key={y} x1="0" x2="760" y1={y} y2={y}/>)}{[80,240,400,560,720].map(x=><line key={x} x1={x} x2={x} y1="0" y2="240"/>)}</g><path className="chart-line secondary" d="M0 190 C70 200 92 168 145 178 S220 154 268 165 S350 128 400 140 S480 105 530 118 S630 70 760 82"/><path className="chart-line primary" d="M0 210 C65 196 100 205 145 183 S215 190 268 151 S340 160 400 124 S475 138 530 98 S640 108 760 52"/><circle cx="760" cy="52" r="4" className="chart-dot"/></svg><div className="chart-x"><span>01:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>Сейчас</span></div><div className="chart-tooltip"><b>{oi ? '$68.42B' : '$2.73T'}</b><span>08:47 UTC</span></div></div> }
function Gauge() { return <div className="gauge"><svg viewBox="0 0 220 120" aria-label="Индекс страха и жадности 74"><path d="M25 105 A85 85 0 0 1 195 105" pathLength="100" className="gauge-track"/><path d="M25 105 A85 85 0 0 1 195 105" pathLength="100" className="gauge-progress" strokeDasharray="74 100"/><line x1="110" y1="105" x2="161" y2="56" className="gauge-needle"/><circle cx="110" cy="105" r="5"/></svg><strong>74</strong><span>Жадность</span></div> }


export function DemoMarketPanels({asset}:{asset:Exclude<Asset,'Обзор'>}) {
const selected=data[asset];
return <><p className="context-note">Обзор рынка · демонстрационный срез 24ч. Фильтры карты выше относятся только к модулю ликвидаций.</p>  <div className="derivatives-grid"><Section title="Цена + открытый интерес · пример формы" action={<span className="updated-label">Фиксированный срез · 24ч</span>}><div className="big-stat"><strong>{selected.price}</strong><span className={selected.change.startsWith('-')?'negative':'positive'}>{selected.change}</span><small>Цена · Open Interest {selected.oi} <b className="positive">{selected.oiChange}</b></small></div><div className="legend"><span><i className="dot gold"/>Цена</span><span><i className="dot blue"/>Open Interest</span></div><Chart oi/><div className="movement-structure"><b>СТРУКТУРА ДВИЖЕНИЯ</b><div><span>Цена <strong className={selected.change.startsWith('-')?'negative':'positive'}>{selected.change}</strong></span><span>Open Interest <strong className="positive">↑ {selected.oiChange}</strong></span></div><p>Новый леверидж входит в рынок</p></div><Fresh/></Section><Section title="Соотношение Long / Short" action={<span className="updated-label"><Clock3/> 8ч интервал</span>}><div className="positioning"><div className="position-total"><b>54.8%</b><span>Long</span><b>45.2%</b><span>Short</span></div><div className="split-bar"><i/><b/></div><div className="position-rows"><Metric label="Сейчас" value="54.8 / 45.2"/><Metric label="24ч назад" value="51.4 / 48.6"/><Metric label="7д среднее" value="49.8 / 50.2"/><Metric label="90д перцентиль" value="84%" note="Выше нормы"/></div><div className="history-spark"><Spark/></div></div><Fresh/></Section></div>
  <div className="analytics-two-col"><Section title="Давление левериджа"><div className="pressure-head"><strong>{leverageComposite}</strong><span>/ 100 · Высокое</span></div><div className="pressure-metrics"><Metric label="Расширение OI" value={`${leverageMetrics[0]}`}/><Metric label="Давление funding" value={`${leverageMetrics[1]}`}/><Metric label="Дисбаланс позиций" value={`${leverageMetrics[2]}`}/><Metric label="Концентрация ликвидаций" value={`${leverageMetrics[3]}`}/></div><small className="panel-footnote">Измерение структуры рынка, не торговый сигнал.</small></Section><Section title="Структура рынка"><div className="structure-table">{[['Текущая цена',selected.price],['Максимум / минимум за 7д',`${selected.high} — ${selected.low}`],['Объём относительно среднего за 30д','+28%'],['OI относительно среднего за 30д','+41%'],['Перцентиль funding','82%'],['Перцентиль реализованной волатильности','81%']].map(x=><Metric key={x[0]} label={x[0]} value={x[1]}/>)}</div><Fresh/></Section></div>
  <div className="analytics-three-col"><Section title="Волатильность"><div className="vol-stat"><strong>{selected.vol}</strong><span>{asset} реализованная · 24ч</span><Spark/></div><Metric label="7д" value="39.4%"/><Metric label="30д" value="34.1%"/><Metric label="90д перцентиль" value="81%" note="Повышенная"/></Section><Section title="Базис фьючерсов"><div className="basis-compact"><div className="basis-chart"><svg viewBox="0 0 300 130" preserveAspectRatio="none" aria-label="Кривая фьючерсного базиса"><path d="M5 105 C55 93 78 92 120 76 S185 50 230 42 S270 35 295 24"/></svg><div><span>Спот</span><span>Perpetual</span><span>1M</span><span>3M</span><span>6M</span></div></div><div className="basis-assets"><Metric label="BTC" value={data.BTC.basis} tone="positive"/><Metric label="ETH" value="+0.61%" tone="positive"/><Metric label="SOL" value="+1.24%" tone="positive"/><Metric label="Состояние" value="Контанго" tone="attention"/></div></div></Section><Section title="Ширина рынка"><div className="breadth-bar"><i style={{width:'68%'}}/><b>68% в плюсе</b></div><Metric label="Активы в плюсе 24ч" value="68%" tone="positive"/><Metric label="Выше среднего за 7д" value="61%"/><Metric label="Новые максимумы / минимумы 30д" value="42 / 11"/></Section></div>
  <Section title="Ставки финансирования"><div className="funding-context"><Metric label="Текущий средний" value="+0.0084%" tone="positive"/><Metric label="Среднее за 7д" value="+0.0047%"/><Metric label="Среднее за 30д" value="+0.0039%"/><Metric label="Перцентиль за 90д" value="82%"/><Metric label="Отклонение от 7д" value="+78%" tone="attention"/><Metric label="Положительный funding" value="72%" tone="positive"/></div><div className="funding-extremes"><span><Coin ticker="SOL"/> +0.031% <b className="attention">Перегрет</b></span><span><Coin ticker="BTC"/> +0.008% <b>Нейтрально</b></span><span><Coin ticker="XRP"/> -0.018% <b className="negative">Отрицательный</b></span></div><div className="heatmap-scroll"><table className="heatmap funding-table"><thead><tr><th>Актив</th>{['Сейчас','8ч','24ч','3д','7д'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{funding.map(row=><tr key={row[0]}><td><Coin ticker={row[0]}/></td>{row.slice(1).map((v,i)=><td className={v.startsWith('-')?'heat-negative':i===0?'heat-positive':'heat-soft'} key={i}>{v}</td>)}</tr>)}</tbody></table></div><Fresh/></Section>
  <div className="intelligence-grid"><Section title="ETF потоки"><div className="flow-kpis"><Metric label="Сегодня" value="+$286M" tone="positive"/><Metric label="Среднее за 5д" value="+$174M"/><Metric label="Среднее за 20д" value="+$92M"/><Metric label="Разница с 5д" value="+64%" tone="positive"/><Metric label="Текущая серия" value="4 дня притока"/></div><div className="flow-bars">{['IBIT','FBTC','ARKB','BITB','Другие'].map((x,i)=><div key={x}><span>{x}</span><i style={{height:`${35+i*11}%`}}/></div>)}</div><Fresh/></Section><Section title="Потоки на биржи"><Metric label="Чистый поток BTC" value="-6.3K BTC" tone="positive"/><Metric label="Среднее за 7д" value="-2.1K BTC"/><Metric label="Среднее за 30д" value="-1.4K BTC"/><Metric label="Отклонение" value="-200%" tone="attention"/><div className="reserve-trend"><span>Резервы на биржах</span><b>7д ↓</b><b>30д ↓</b><b>90д ↓</b></div><Fresh/></Section></div>
  <Section title="Активность крупных держателей"><div className="whale-context"><Metric label="Крупные транзакции 24ч" value="1,284"/><Metric label="Среднее за 7д" value="938"/><Metric label="Изменение" value="+36.9%" tone="positive"/><Metric label="Объём >$10M" value="$4.82B"/><Metric label="Объём >$100M" value="$1.16B"/></div><div className="whale-split"><span>На биржи <b>38%</b></span><span>С бирж <b>47%</b></span><span>Между кошельками <b>15%</b></span><strong>Активность · Выше нормы</strong></div><Fresh/></Section>
  <div className="analytics-two-col"><Section title="Корреляция рынка" action={<span className="updated-label">Фиксированный срез · 24ч</span>}><div className="correlation"><div></div>{['BTC','ETH','SOL','XRP','NASDAQ','Золото'].map(x=><b key={x}>{x}</b>)}{['BTC','ETH','SOL','XRP','NASDAQ','Золото'].map((row,i)=><div key={row}><b>{row}</b>{[1,.82,.67,.54,.31,-.08].map((_,j)=><span key={j} style={{opacity:.35+Math.abs(i-j)*.09}}>{(1-Math.abs(i-j)*.13).toFixed(2)}</span>)}</div>)}</div></Section><Section title="Индекс страха и жадности"><div className="fear-panel"><Gauge/><div className="comparisons">{[['Вчера','69'],['Неделю назад','61'],['Месяц назад','54']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div><Fresh/></Section></div>
  <Section title="Сектора рынка"><div className="table-scroll"><table><thead><tr>{['Сектор','24ч','7д','Капитализация','Объём'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{sectors.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td>{r.slice(1).map((x,i)=><td className={i<2&&x.startsWith('+')?'positive':x.startsWith('-')?'negative':''} key={i}>{x}</td>)}</tr>)}</tbody></table></div><Fresh/></Section>
  <Section title="Движение рынка"><div className="movers">{movers.map(x=><div className="mover" key={x[0]}><Coin ticker={x[0]}/><span>{x[1]}</span><b className={x[2].startsWith('+')?'positive':'negative'}>{x[2]}</b><small>{x[3]}</small></div>)}</div><Fresh/></Section>
</>
}
function Spark(){return <svg className="sparkline" viewBox="0 0 150 48" preserveAspectRatio="none"><path className="spark-teal" d="M0 36 C20 29 24 33 40 26 S65 30 78 19 S102 25 116 15 S137 20 150 10"/></svg>}
