const en = {
  notice: 'Orders do not reach the real market. Funds and positions are for testing.',
  pair: 'Pair', positions: 'Positions', active: 'Open orders', orders: 'Order history', fills: 'Trades',
  empty: 'No records yet', average: 'Average entry', mark: 'Mark', unrealized: 'Unrealized PnL', realized: 'Realized PnL',
  available: 'Available', reserved: 'Reserved', quantity: 'Amount', price: 'Price', total: 'Total',
  cancel: 'Cancel', half: 'Sell 50%', all: 'Sell all', source: 'Execution price', refresh: 'Refresh price',
  settings: 'Test wallet settings', apply: 'Apply settings', balance: 'Test balance', fee: 'Fee', feeBps: 'Fee, basis points',
  conversion: 'Fixed test conversion', conversionHelp: 'This is a test accounting rate, not a market stablecoin quote. USD price ÷ this rate = pair price.',
  settingsLocked: 'Rates and fees are locked after the first order. Test balance changes are recorded separately.',
  sent: 'Order accepted', cancelled: 'Order cancelled', configured: 'Test wallet configured',
  waiting: 'Loading local account…', unavailable: 'Local simulator is unavailable', retry: 'Retry',
  age: 'Age', seconds: 's', min: '1-minute quote', status: 'Status', filled: 'Filled', open: 'Open', cancelledStatus: 'Cancelled',
  time: 'Time', noQuote: 'No verified execution price', unknown: 'Request failed. Retry safely; the same request will not execute twice.',
  errors: {
    RESERVED_FUNDS: 'Test balance cannot be lower than reserved funds.',
    QUOTE_UNAVAILABLE: 'No verified quote. Refresh the price.', QUOTE_STALE: 'Quote is outdated. Execution is blocked.',
    MARKET_CLOSED: 'Regular market session is closed.', SOURCE_KEY_REQUIRED: 'A private quote-provider API key is required for this instrument.',
    PROVIDER_UNAVAILABLE: 'Quote provider is unavailable.', PROVIDER_RATE_LIMIT: 'Provider quota reached. Wait before refreshing.',
    PROVIDER_BUSY: 'Quote refresh is already running.', INVALID_QUOTE: 'Quote validation failed.',
    INSUFFICIENT_FUNDS: 'Insufficient available test funds.', INSUFFICIENT_SHARES: 'Insufficient available shares.',
    INVALID_DECIMAL: 'Enter a decimal with up to 8 digits after the decimal point.', INVALID_AMOUNT: 'Amount is outside the allowed range.',
    INVALID_RATE: 'Test conversion rate must be between 0.1 and 10 USD.', INVALID_FEE: 'Fee must be an integer from 0 to 1000 basis points.',
    SETTINGS_LOCKED: 'Settings are locked after the first order.', ORDER_TOO_SMALL: 'Order amount is too small.',
    IDEMPOTENCY_CONFLICT: 'Request ID already belongs to another order.', TOKEN_REQUIRED: 'Reload the local preview.',
  } as Record<string, string>,
};
type Text = typeof en;
const ru: Text = { ...en,
  notice: 'Заявки не выходят на реальный рынок. Средства и позиции — тестовые.',
  pair: 'Пара', positions: 'Позиции', active: 'Активные заявки', orders: 'История ордеров', fills: 'Сделки',
  empty: 'Пока нет записей', average: 'Средняя входа', mark: 'Оценка', unrealized: 'Нереализованный PnL', realized: 'Реализованный PnL',
  available: 'Доступно', reserved: 'В резерве', quantity: 'Количество', price: 'Цена', total: 'Итого',
  cancel: 'Отменить', half: 'Продать 50%', all: 'Продать всё', source: 'Цена исполнения', refresh: 'Обновить цену',
  settings: 'Настройки тестового кошелька', apply: 'Применить настройки', balance: 'Тестовый баланс', fee: 'Комиссия', feeBps: 'Комиссия, базисные пункты',
  conversion: 'Фиксированный тестовый курс', conversionHelp: 'Это правило тестового учёта, а не рыночная котировка стейблкоина. Цена USD ÷ курс = цена пары.',
  settingsLocked: 'Курсы и комиссия фиксируются после первой заявки. Изменения тестового баланса сохраняются отдельно.',
  sent: 'Заявка принята', cancelled: 'Заявка отменена', configured: 'Тестовый кошелёк настроен',
  waiting: 'Загрузка локального счёта…', unavailable: 'Локальный симулятор недоступен', retry: 'Повторить',
  age: 'Возраст', seconds: 'с', min: 'Котировка за 1 минуту', status: 'Статус', filled: 'Исполнен', open: 'Активен', cancelledStatus: 'Отменён',
  time: 'Время', noQuote: 'Нет подтверждённой цены исполнения', unknown: 'Запрос не завершён. Повтор безопасен: одна заявка не исполнится дважды.',
  errors: { ...en.errors,
    RESERVED_FUNDS: 'Тестовый баланс не может быть меньше зарезервированных средств.',
    QUOTE_UNAVAILABLE: 'Нет подтверждённой цены. Обновите котировку.', QUOTE_STALE: 'Котировка устарела. Исполнение заблокировано.',
    MARKET_CLOSED: 'Основная торговая сессия закрыта.', SOURCE_KEY_REQUIRED: 'Для этого инструмента нужен собственный API-ключ поставщика котировок.',
    PROVIDER_UNAVAILABLE: 'Поставщик котировок недоступен.', PROVIDER_RATE_LIMIT: 'Достигнут лимит запросов. Дождитесь обновления.',
    PROVIDER_BUSY: 'Котировка уже обновляется.', INVALID_QUOTE: 'Котировка не прошла проверку.',
    INSUFFICIENT_FUNDS: 'Недостаточно доступных тестовых средств.', INSUFFICIENT_SHARES: 'Недостаточно доступных акций.',
    INVALID_DECIMAL: 'Введите число, до 8 знаков после точки.', INVALID_AMOUNT: 'Количество вне допустимого диапазона.',
    INVALID_RATE: 'Тестовый курс должен быть от 0.1 до 10 USD.', INVALID_FEE: 'Комиссия: целое число от 0 до 1000 базисных пунктов.',
    SETTINGS_LOCKED: 'Настройки зафиксированы после первой заявки.', ORDER_TOO_SMALL: 'Сумма заявки слишком мала.',
    IDEMPOTENCY_CONFLICT: 'Этот идентификатор уже принадлежит другой заявке.', TOKEN_REQUIRED: 'Перезагрузите локальный preview.',
  },
};
const uk: Text = { ...en,
  notice: 'Заявки не виходять на реальний ринок. Кошти й позиції — тестові.',
  pair: 'Пара', positions: 'Позиції', active: 'Активні заявки', orders: 'Історія ордерів', fills: 'Операції',
  empty: 'Записів ще немає', average: 'Середня входу', mark: 'Оцінка', unrealized: 'Нереалізований PnL', realized: 'Реалізований PnL',
  available: 'Доступно', reserved: 'У резерві', quantity: 'Кількість', price: 'Ціна', total: 'Разом',
  cancel: 'Скасувати', half: 'Продати 50%', all: 'Продати все', source: 'Ціна виконання', refresh: 'Оновити ціну',
  settings: 'Налаштування тестового гаманця', apply: 'Застосувати налаштування', balance: 'Тестовий баланс', fee: 'Комісія', feeBps: 'Комісія, базисні пункти',
  conversion: 'Фіксований тестовий курс', conversionHelp: 'Це правило тестового обліку, а не ринкова котировка стейблкоїна. Ціна USD ÷ курс = ціна пари.',
  settingsLocked: 'Курси й комісія фіксуються після першої заявки. Зміни тестового балансу зберігаються окремо.',
  sent: 'Заявку прийнято', cancelled: 'Заявку скасовано', configured: 'Тестовий гаманець налаштовано',
  waiting: 'Завантаження локального рахунку…', unavailable: 'Локальний симулятор недоступний', retry: 'Повторити',
  age: 'Вік', seconds: 'с', min: 'Котировка за 1 хвилину', status: 'Статус', filled: 'Виконано', open: 'Активний', cancelledStatus: 'Скасовано',
  time: 'Час', noQuote: 'Немає підтвердженої ціни виконання', unknown: 'Запит не завершено. Повтор безпечний: одна заявка не виконається двічі.',
  errors: { ...en.errors,
    RESERVED_FUNDS: 'Тестовий баланс не може бути меншим за зарезервовані кошти.',
    QUOTE_UNAVAILABLE: 'Немає підтвердженої ціни. Оновіть котировку.', QUOTE_STALE: 'Котировка застаріла. Виконання заблоковано.',
    MARKET_CLOSED: 'Основна торгова сесія закрита.', SOURCE_KEY_REQUIRED: 'Для цього інструмента потрібен власний API-ключ поставщика котировок.',
    PROVIDER_UNAVAILABLE: 'Постачальник котирувань недоступний.', PROVIDER_RATE_LIMIT: 'Досягнуто ліміт запитів. Дочекайтеся оновлення.',
    PROVIDER_BUSY: 'Котировка вже оновлюється.', INVALID_QUOTE: 'Котировка не пройшла перевірку.',
    INSUFFICIENT_FUNDS: 'Недостатньо доступних тестових коштів.', INSUFFICIENT_SHARES: 'Недостатньо доступних акцій.',
    INVALID_DECIMAL: 'Введіть число, до 8 знаків після крапки.', INVALID_AMOUNT: 'Кількість поза допустимим діапазоном.',
    INVALID_RATE: 'Тестовий курс має бути від 0.1 до 10 USD.', INVALID_FEE: 'Комісія: ціле число від 0 до 1000 базисних пунктів.',
    SETTINGS_LOCKED: 'Налаштування зафіксовано після першої заявки.', ORDER_TOO_SMALL: 'Сума заявки замала.',
    IDEMPOTENCY_CONFLICT: 'Цей ідентифікатор належить іншій заявці.', TOKEN_REQUIRED: 'Перезавантажте локальний preview.',
  },
};
export const simulatorText = (lang: string): Text => lang === 'ru' ? ru : lang === 'uk' ? uk : en;
