import type { CSSProperties } from 'react';

/** Shared style tokens for the /admin panel — same visual language as the
 * rest of the exchange (see SettingsPage's own `styles`), just laid out as
 * a sidebar shell instead of a tab strip since this is a separate section,
 * not one more Settings tab. */
export const styles: Record<string, CSSProperties> = {
  loadingScreen: { minHeight: '100vh', background: 'var(--bg)' },
  page: { minHeight: '100vh', background: 'var(--bg)', display: 'grid', gridTemplateColumns: '220px 1fr' },
  sidebar: {
    borderRight: '1px solid var(--border)',
    padding: '24px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    position: 'sticky',
    top: 0,
    height: '100vh',
  },
  sidebarTitle: {
    fontFamily: 'var(--font-display)',
    fontWeight: 800,
    fontSize: 15,
    letterSpacing: '-0.01em',
    padding: '0 12px 16px',
  },
  nav: { display: 'flex', flexDirection: 'column', gap: 2 },
  navItem: {
    textDecoration: 'none',
    color: 'var(--text-secondary)',
    fontSize: 13,
    padding: '9px 12px',
    borderRadius: 8,
  },
  navItemActive: { background: 'var(--panel)', color: 'var(--text-primary)', fontWeight: 600 },
  soundToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '9px 12px',
    fontSize: 12,
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  main: { padding: '32px 40px', maxWidth: 1200, minWidth: 0 },
  title: { fontSize: 20, marginBottom: 20, fontFamily: 'var(--font-display)', fontWeight: 800, letterSpacing: '-0.01em' },
  card: {
    background: 'var(--panel)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  table: {
    background: 'var(--panel)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    overflow: 'hidden',
    overflowX: 'auto',
  },
  tableHeader: {
    display: 'grid',
    padding: '10px 14px',
    fontSize: 11,
    color: 'var(--text-tertiary)',
    borderBottom: '1px solid var(--border)',
    gap: 8,
  },
  tableRow: {
    display: 'grid',
    padding: '10px 14px',
    fontSize: 13,
    alignItems: 'center',
    borderTop: '1px solid var(--border)',
    gap: 8,
  },
  row: { display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid var(--border)' },
  form: { display: 'flex', flexDirection: 'column', gap: 14 },
  label: { display: 'flex', flexDirection: 'column', gap: 5, fontSize: 11, color: 'var(--text-secondary)' },
  input: {
    background: 'var(--panel-alt)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '9px 10px',
    color: 'var(--text-primary)',
    fontSize: 13,
  },
  hint: { fontSize: 11, color: 'var(--text-tertiary)' },
  errorBox: { background: 'var(--sell-dim)', color: 'var(--sell)', padding: '8px 10px', borderRadius: 8, fontSize: 12 },
  successBox: { background: 'var(--buy-dim)', color: 'var(--buy)', padding: '8px 10px', borderRadius: 8, fontSize: 12 },
  primaryBtn: {
    background: 'var(--accent)',
    color: 'var(--on-accent)',
    border: 'none',
    borderRadius: 20,
    padding: '9px 18px',
    fontWeight: 700,
    fontSize: 13,
  },
  approveBtn: {
    background: 'var(--buy)',
    color: 'var(--on-accent)',
    border: 'none',
    borderRadius: 20,
    padding: '8px 16px',
    fontWeight: 700,
    fontSize: 12,
  },
  rejectBtn: {
    background: 'transparent',
    color: 'var(--sell)',
    border: '1px solid var(--sell)',
    borderRadius: 20,
    padding: '8px 16px',
    fontWeight: 700,
    fontSize: 12,
  },
  neutralBtn: {
    background: 'transparent',
    color: 'var(--text-secondary)',
    border: '1px solid var(--border)',
    borderRadius: 20,
    padding: '8px 16px',
    fontWeight: 600,
    fontSize: 12,
  },
  badgeDim: { color: 'var(--text-secondary)', background: 'var(--neutral-dim)' },
  badgeAccent: { color: 'var(--accent)', background: 'var(--accent-dim)' },
  badgeBuy: { color: 'var(--buy)', background: 'var(--buy-dim)' },
  badgeSell: { color: 'var(--sell)', background: 'var(--sell-dim)' },
};
