export type CfdUiLang = 'ru'|'en'|'zh'|'es'|'hi'|'ja'|'ko';

export interface CfdDisplayCopy {
  live:string; marketClosed:string; lastQuote:string; priceUnavailable:string;
  marketOverview:string; marketPrice:string; status:string; session:string; open:string; closed:string; unavailable:string;
  updated:string; quote:string; feed:string; multiSource:string; market:string;
  metal:string; energy:string; fxMajor:string;
  note:string; dataCoverage:string; instrumentsMulti:string; metals:string; fxMajors:string; resilience:string;
  primaryReserve:string; displayOnly:string; chartNote:string;
  practice:string; practiceNote:string; practiceStored:string;
}

const COPY:Record<CfdUiLang,CfdDisplayCopy>={
  ru:{live:'Онлайн',marketClosed:'Рынок закрыт',lastQuote:'Последняя цена',priceUnavailable:'Цена недоступна',marketOverview:'Обзор рынка',marketPrice:'Рыночная цена',status:'Статус',session:'Сессия',open:'Открыта',closed:'Закрыта',unavailable:'Недоступно',updated:'Обновлено',quote:'Инструмент',feed:'Источник',multiSource:'Несколько источников',market:'Рынок',metal:'Драгоценный металл',energy:'Энергия',fxMajor:'Основная валютная пара',note:'VOLTEX автоматически выбирает доступный источник. Отсутствующие цены не рассчитываются и не подменяются.',dataCoverage:'Покрытие рынка',instrumentsMulti:'13 инструментов · несколько источников',metals:'Металлы',fxMajors:'Основные FX',resilience:'Резервирование',primaryReserve:'Основной + резервный + последняя подтверждённая цена',displayOnly:'Котировки используются только для отображения. VOLTEX автоматически переключает источники и не подставляет расчётные значения.',chartNote:'Рыночные данные для отображения. Источник переключается автоматически.',practice:'Практика',practiceNote:'Ордера рассчитываются по текущей отображаемой котировке и не отправляются на внешний рынок.',practiceStored:'Позиции практики сохраняются только в этом браузере.'},
  en:{live:'Live',marketClosed:'Market closed',lastQuote:'Last quote',priceUnavailable:'Price unavailable',marketOverview:'Market overview',marketPrice:'Market price',status:'Status',session:'Session',open:'Open',closed:'Closed',unavailable:'Unavailable',updated:'Updated',quote:'Instrument',feed:'Feed',multiSource:'Multi-source',market:'Market',metal:'Precious metal',energy:'Energy',fxMajor:'FX major',note:'VOLTEX automatically routes to an available source. Missing prices are never estimated or substituted.',dataCoverage:'Market data coverage',instrumentsMulti:'13 instruments · multi-source',metals:'Metals',fxMajors:'FX majors',resilience:'Resilience',primaryReserve:'Primary + reserve + last verified quote',displayOnly:'Prices are display data only. VOLTEX switches sources automatically and never fills a missing quote with an estimated value.',chartNote:'Market data for display. The source switches automatically.',practice:'Practice',practiceNote:'Orders are calculated from the displayed market quote and are never sent to an external market.',practiceStored:'Practice positions are stored only in this browser.'},
  zh:{live:'实时',marketClosed:'市场已休市',lastQuote:'最后报价',priceUnavailable:'价格不可用',marketOverview:'市场概览',marketPrice:'市场价格',status:'状态',session:'交易时段',open:'开放',closed:'已关闭',unavailable:'不可用',updated:'更新时间',quote:'品种',feed:'数据源',multiSource:'多数据源',market:'市场',metal:'贵金属',energy:'能源',fxMajor:'主要外汇',note:'VOLTEX 会自动选择可用数据源。缺失价格不会被估算或替代。',dataCoverage:'市场数据覆盖',instrumentsMulti:'13 个品种 · 多数据源',metals:'金属',fxMajors:'主要外汇',resilience:'冗余',primaryReserve:'主源 + 备用源 + 最后确认报价',displayOnly:'价格仅用于展示。VOLTEX 会自动切换数据源，不会用估算值填补缺失报价。',chartNote:'市场数据仅用于展示，数据源会自动切换。',practice:'练习',practiceNote:'订单按当前显示的市场报价计算，不会发送到外部市场。',practiceStored:'练习仓位仅保存在此浏览器中。'},
  es:{live:'En vivo',marketClosed:'Mercado cerrado',lastQuote:'Última cotización',priceUnavailable:'Precio no disponible',marketOverview:'Resumen del mercado',marketPrice:'Precio de mercado',status:'Estado',session:'Sesión',open:'Abierta',closed:'Cerrada',unavailable:'No disponible',updated:'Actualizado',quote:'Instrumento',feed:'Fuente',multiSource:'Varias fuentes',market:'Mercado',metal:'Metal precioso',energy:'Energía',fxMajor:'FX principal',note:'VOLTEX selecciona automáticamente una fuente disponible. Los precios ausentes no se estiman ni se sustituyen.',dataCoverage:'Cobertura de datos',instrumentsMulti:'13 instrumentos · varias fuentes',metals:'Metales',fxMajors:'FX principales',resilience:'Redundancia',primaryReserve:'Principal + reserva + última cotización verificada',displayOnly:'Los precios son solo informativos. VOLTEX cambia de fuente automáticamente y nunca rellena una cotización ausente con un valor estimado.',chartNote:'Datos de mercado para visualización. La fuente cambia automáticamente.',practice:'Práctica',practiceNote:'Las órdenes se calculan con la cotización mostrada y nunca se envían a un mercado externo.',practiceStored:'Las posiciones de práctica se guardan solo en este navegador.'},
  hi:{live:'लाइव',marketClosed:'बाज़ार बंद',lastQuote:'अंतिम भाव',priceUnavailable:'कीमत उपलब्ध नहीं',marketOverview:'बाज़ार अवलोकन',marketPrice:'बाज़ार मूल्य',status:'स्थिति',session:'सत्र',open:'खुला',closed:'बंद',unavailable:'उपलब्ध नहीं',updated:'अपडेट',quote:'इंस्ट्रूमेंट',feed:'स्रोत',multiSource:'मल्टी-सोर्स',market:'बाज़ार',metal:'कीमती धातु',energy:'ऊर्जा',fxMajor:'प्रमुख FX',note:'VOLTEX उपलब्ध स्रोत अपने आप चुनता है। गायब कीमतों का अनुमान या प्रतिस्थापन नहीं किया जाता।',dataCoverage:'मार्केट डेटा कवरेज',instrumentsMulti:'13 इंस्ट्रूमेंट · मल्टी-सोर्स',metals:'धातु',fxMajors:'प्रमुख FX',resilience:'रिज़र्व',primaryReserve:'प्राइमरी + रिज़र्व + अंतिम सत्यापित भाव',displayOnly:'कीमतें केवल प्रदर्शन के लिए हैं। VOLTEX स्रोत अपने आप बदलता है और गायब भाव को अनुमानित मान से नहीं भरता।',chartNote:'प्रदर्शन के लिए मार्केट डेटा। स्रोत अपने आप बदलता है।',practice:'प्रैक्टिस',practiceNote:'ऑर्डर दिखाई गई मार्केट कीमत पर गणना होते हैं और किसी बाहरी मार्केट में नहीं भेजे जाते।',practiceStored:'प्रैक्टिस पोज़िशन केवल इस ब्राउज़र में सेव रहती हैं।'},
  ja:{live:'ライブ',marketClosed:'市場休場',lastQuote:'最終価格',priceUnavailable:'価格を取得できません',marketOverview:'市場概要',marketPrice:'市場価格',status:'ステータス',session:'セッション',open:'取引中',closed:'休場',unavailable:'利用不可',updated:'更新',quote:'銘柄',feed:'データ源',multiSource:'複数ソース',market:'市場',metal:'貴金属',energy:'エネルギー',fxMajor:'主要FX',note:'VOLTEX は利用可能なデータ源を自動選択します。欠損価格を推定・代替しません。',dataCoverage:'市場データ範囲',instrumentsMulti:'13銘柄 · 複数ソース',metals:'金属',fxMajors:'主要FX',resilience:'冗長化',primaryReserve:'メイン + 予備 + 最終確認価格',displayOnly:'価格は表示専用です。VOLTEX はデータ源を自動で切り替え、欠損価格を推定値で補いません。',chartNote:'表示用の市場データです。データ源は自動的に切り替わります。',practice:'練習',practiceNote:'注文は表示中の市場価格で計算され、外部市場には送信されません。',practiceStored:'練習ポジションはこのブラウザにのみ保存されます。'},
  ko:{live:'실시간',marketClosed:'시장 마감',lastQuote:'마지막 시세',priceUnavailable:'가격 없음',marketOverview:'시장 개요',marketPrice:'시장 가격',status:'상태',session:'세션',open:'개장',closed:'마감',unavailable:'사용 불가',updated:'업데이트',quote:'종목',feed:'데이터 소스',multiSource:'다중 소스',market:'시장',metal:'귀금속',energy:'에너지',fxMajor:'주요 FX',note:'VOLTEX는 사용 가능한 데이터 소스를 자동 선택합니다. 누락된 가격을 추정하거나 대체하지 않습니다.',dataCoverage:'시장 데이터 범위',instrumentsMulti:'13개 종목 · 다중 소스',metals:'금속',fxMajors:'주요 FX',resilience:'이중화',primaryReserve:'주 소스 + 예비 소스 + 마지막 확인 시세',displayOnly:'가격은 표시 전용입니다. VOLTEX는 소스를 자동 전환하며 누락된 시세를 추정값으로 채우지 않습니다.',chartNote:'표시용 시장 데이터입니다. 데이터 소스는 자동 전환됩니다.',practice:'연습',practiceNote:'주문은 화면에 표시된 시세로 계산되며 외부 시장으로 전송되지 않습니다.',practiceStored:'연습 포지션은 이 브라우저에만 저장됩니다.'},
};

export function cfdMarketCopy(lang:string):CfdDisplayCopy{return COPY[lang as CfdUiLang]??COPY.en;}
