import type { Lang } from './i18n';

// ISO 3166-1 alpha-2 codes with Russian, English, and Chinese display
// names, for the verification (KYC) country selector — every country is
// selectable.
const COUNTRIES: { code: string; ru: string; en: string; zh: string }[] = [
  { code: 'AF', ru: 'Афганистан', en: 'Afghanistan', zh: '阿富汗' },
  { code: 'AL', ru: 'Албания', en: 'Albania', zh: '阿尔巴尼亚' },
  { code: 'DZ', ru: 'Алжир', en: 'Algeria', zh: '阿尔及利亚' },
  { code: 'AD', ru: 'Андорра', en: 'Andorra', zh: '安道尔' },
  { code: 'AO', ru: 'Ангола', en: 'Angola', zh: '安哥拉' },
  { code: 'AG', ru: 'Антигуа и Барбуда', en: 'Antigua and Barbuda', zh: '安提瓜和巴布达' },
  { code: 'AR', ru: 'Аргентина', en: 'Argentina', zh: '阿根廷' },
  { code: 'AM', ru: 'Армения', en: 'Armenia', zh: '亚美尼亚' },
  { code: 'AU', ru: 'Австралия', en: 'Australia', zh: '澳大利亚' },
  { code: 'AT', ru: 'Австрия', en: 'Austria', zh: '奥地利' },
  { code: 'AZ', ru: 'Азербайджан', en: 'Azerbaijan', zh: '阿塞拜疆' },
  { code: 'BS', ru: 'Багамы', en: 'Bahamas', zh: '巴哈马' },
  { code: 'BH', ru: 'Бахрейн', en: 'Bahrain', zh: '巴林' },
  { code: 'BD', ru: 'Бангладеш', en: 'Bangladesh', zh: '孟加拉国' },
  { code: 'BB', ru: 'Барбадос', en: 'Barbados', zh: '巴巴多斯' },
  { code: 'BY', ru: 'Беларусь', en: 'Belarus', zh: '白俄罗斯' },
  { code: 'BE', ru: 'Бельгия', en: 'Belgium', zh: '比利时' },
  { code: 'BZ', ru: 'Белиз', en: 'Belize', zh: '伯利兹' },
  { code: 'BJ', ru: 'Бенин', en: 'Benin', zh: '贝宁' },
  { code: 'BT', ru: 'Бутан', en: 'Bhutan', zh: '不丹' },
  { code: 'BO', ru: 'Боливия', en: 'Bolivia', zh: '玻利维亚' },
  { code: 'BA', ru: 'Босния и Герцеговина', en: 'Bosnia and Herzegovina', zh: '波斯尼亚和黑塞哥维那' },
  { code: 'BW', ru: 'Ботсвана', en: 'Botswana', zh: '博茨瓦纳' },
  { code: 'BR', ru: 'Бразилия', en: 'Brazil', zh: '巴西' },
  { code: 'BN', ru: 'Бруней', en: 'Brunei', zh: '文莱' },
  { code: 'BG', ru: 'Болгария', en: 'Bulgaria', zh: '保加利亚' },
  { code: 'BF', ru: 'Буркина-Фасо', en: 'Burkina Faso', zh: '布基纳法索' },
  { code: 'BI', ru: 'Бурунди', en: 'Burundi', zh: '布隆迪' },
  { code: 'KH', ru: 'Камбоджа', en: 'Cambodia', zh: '柬埔寨' },
  { code: 'CM', ru: 'Камерун', en: 'Cameroon', zh: '喀麦隆' },
  { code: 'CA', ru: 'Канада', en: 'Canada', zh: '加拿大' },
  { code: 'CV', ru: 'Кабо-Верде', en: 'Cape Verde', zh: '佛得角' },
  { code: 'CF', ru: 'Центральноафриканская Республика', en: 'Central African Republic', zh: '中非共和国' },
  { code: 'TD', ru: 'Чад', en: 'Chad', zh: '乍得' },
  { code: 'CL', ru: 'Чили', en: 'Chile', zh: '智利' },
  { code: 'CN', ru: 'Китай', en: 'China', zh: '中国' },
  { code: 'CO', ru: 'Колумбия', en: 'Colombia', zh: '哥伦比亚' },
  { code: 'KM', ru: 'Коморские острова', en: 'Comoros', zh: '科摩罗' },
  { code: 'CG', ru: 'Конго', en: 'Congo', zh: '刚果（布）' },
  { code: 'CD', ru: 'Демократическая Республика Конго', en: 'DR Congo', zh: '刚果（金）' },
  { code: 'CR', ru: 'Коста-Рика', en: 'Costa Rica', zh: '哥斯达黎加' },
  { code: 'CI', ru: "Кот-д'Ивуар", en: "Cote d'Ivoire", zh: '科特迪瓦' },
  { code: 'HR', ru: 'Хорватия', en: 'Croatia', zh: '克罗地亚' },
  { code: 'CU', ru: 'Куба', en: 'Cuba', zh: '古巴' },
  { code: 'CY', ru: 'Кипр', en: 'Cyprus', zh: '塞浦路斯' },
  { code: 'CZ', ru: 'Чехия', en: 'Czechia', zh: '捷克' },
  { code: 'DK', ru: 'Дания', en: 'Denmark', zh: '丹麦' },
  { code: 'DJ', ru: 'Джибути', en: 'Djibouti', zh: '吉布提' },
  { code: 'DM', ru: 'Доминика', en: 'Dominica', zh: '多米尼克' },
  { code: 'DO', ru: 'Доминиканская Республика', en: 'Dominican Republic', zh: '多米尼加共和国' },
  { code: 'EC', ru: 'Эквадор', en: 'Ecuador', zh: '厄瓜多尔' },
  { code: 'EG', ru: 'Египет', en: 'Egypt', zh: '埃及' },
  { code: 'SV', ru: 'Сальвадор', en: 'El Salvador', zh: '萨尔瓦多' },
  { code: 'GQ', ru: 'Экваториальная Гвинея', en: 'Equatorial Guinea', zh: '赤道几内亚' },
  { code: 'ER', ru: 'Эритрея', en: 'Eritrea', zh: '厄立特里亚' },
  { code: 'EE', ru: 'Эстония', en: 'Estonia', zh: '爱沙尼亚' },
  { code: 'SZ', ru: 'Эсватини', en: 'Eswatini', zh: '斯威士兰' },
  { code: 'ET', ru: 'Эфиопия', en: 'Ethiopia', zh: '埃塞俄比亚' },
  { code: 'FJ', ru: 'Фиджи', en: 'Fiji', zh: '斐济' },
  { code: 'FI', ru: 'Финляндия', en: 'Finland', zh: '芬兰' },
  { code: 'FR', ru: 'Франция', en: 'France', zh: '法国' },
  { code: 'GA', ru: 'Габон', en: 'Gabon', zh: '加蓬' },
  { code: 'GM', ru: 'Гамбия', en: 'Gambia', zh: '冈比亚' },
  { code: 'GE', ru: 'Грузия', en: 'Georgia', zh: '格鲁吉亚' },
  { code: 'DE', ru: 'Германия', en: 'Germany', zh: '德国' },
  { code: 'GH', ru: 'Гана', en: 'Ghana', zh: '加纳' },
  { code: 'GR', ru: 'Греция', en: 'Greece', zh: '希腊' },
  { code: 'GD', ru: 'Гренада', en: 'Grenada', zh: '格林纳达' },
  { code: 'GT', ru: 'Гватемала', en: 'Guatemala', zh: '危地马拉' },
  { code: 'GN', ru: 'Гвинея', en: 'Guinea', zh: '几内亚' },
  { code: 'GW', ru: 'Гвинея-Бисау', en: 'Guinea-Bissau', zh: '几内亚比绍' },
  { code: 'GY', ru: 'Гайана', en: 'Guyana', zh: '圭亚那' },
  { code: 'HT', ru: 'Гаити', en: 'Haiti', zh: '海地' },
  { code: 'HN', ru: 'Гондурас', en: 'Honduras', zh: '洪都拉斯' },
  { code: 'HK', ru: 'Гонконг', en: 'Hong Kong', zh: '中国香港' },
  { code: 'HU', ru: 'Венгрия', en: 'Hungary', zh: '匈牙利' },
  { code: 'IS', ru: 'Исландия', en: 'Iceland', zh: '冰岛' },
  { code: 'IN', ru: 'Индия', en: 'India', zh: '印度' },
  { code: 'ID', ru: 'Индонезия', en: 'Indonesia', zh: '印度尼西亚' },
  { code: 'IR', ru: 'Иран', en: 'Iran', zh: '伊朗' },
  { code: 'IQ', ru: 'Ирак', en: 'Iraq', zh: '伊拉克' },
  { code: 'IE', ru: 'Ирландия', en: 'Ireland', zh: '爱尔兰' },
  { code: 'IL', ru: 'Израиль', en: 'Israel', zh: '以色列' },
  { code: 'IT', ru: 'Италия', en: 'Italy', zh: '意大利' },
  { code: 'JM', ru: 'Ямайка', en: 'Jamaica', zh: '牙买加' },
  { code: 'JP', ru: 'Япония', en: 'Japan', zh: '日本' },
  { code: 'JO', ru: 'Иордания', en: 'Jordan', zh: '约旦' },
  { code: 'KZ', ru: 'Казахстан', en: 'Kazakhstan', zh: '哈萨克斯坦' },
  { code: 'KE', ru: 'Кения', en: 'Kenya', zh: '肯尼亚' },
  { code: 'KI', ru: 'Кирибати', en: 'Kiribati', zh: '基里巴斯' },
  { code: 'KP', ru: 'Северная Корея', en: 'North Korea', zh: '朝鲜' },
  { code: 'KR', ru: 'Южная Корея', en: 'South Korea', zh: '韩国' },
  { code: 'XK', ru: 'Косово', en: 'Kosovo', zh: '科索沃' },
  { code: 'KW', ru: 'Кувейт', en: 'Kuwait', zh: '科威特' },
  { code: 'KG', ru: 'Киргизстан', en: 'Kyrgyzstan', zh: '吉尔吉斯斯坦' },
  { code: 'LA', ru: 'Лаос', en: 'Laos', zh: '老挝' },
  { code: 'LV', ru: 'Латвия', en: 'Latvia', zh: '拉脱维亚' },
  { code: 'LB', ru: 'Ливан', en: 'Lebanon', zh: '黎巴嫩' },
  { code: 'LS', ru: 'Лесото', en: 'Lesotho', zh: '莱索托' },
  { code: 'LR', ru: 'Либерия', en: 'Liberia', zh: '利比里亚' },
  { code: 'LY', ru: 'Ливия', en: 'Libya', zh: '利比亚' },
  { code: 'LI', ru: 'Лихтенштейн', en: 'Liechtenstein', zh: '列支敦士登' },
  { code: 'LT', ru: 'Литва', en: 'Lithuania', zh: '立陶宛' },
  { code: 'LU', ru: 'Люксембург', en: 'Luxembourg', zh: '卢森堡' },
  { code: 'MO', ru: 'Макао', en: 'Macau', zh: '中国澳门' },
  { code: 'MG', ru: 'Мадагаскар', en: 'Madagascar', zh: '马达加斯加' },
  { code: 'MW', ru: 'Малави', en: 'Malawi', zh: '马拉维' },
  { code: 'MY', ru: 'Малайзия', en: 'Malaysia', zh: '马来西亚' },
  { code: 'MV', ru: 'Мальдивы', en: 'Maldives', zh: '马尔代夫' },
  { code: 'ML', ru: 'Мали', en: 'Mali', zh: '马里' },
  { code: 'MT', ru: 'Мальта', en: 'Malta', zh: '马耳他' },
  { code: 'MH', ru: 'Маршалловы Острова', en: 'Marshall Islands', zh: '马绍尔群岛' },
  { code: 'MR', ru: 'Мавритания', en: 'Mauritania', zh: '毛里塔尼亚' },
  { code: 'MU', ru: 'Маврикий', en: 'Mauritius', zh: '毛里求斯' },
  { code: 'MX', ru: 'Мексика', en: 'Mexico', zh: '墨西哥' },
  { code: 'FM', ru: 'Микронезия', en: 'Micronesia', zh: '密克罗尼西亚' },
  { code: 'MD', ru: 'Молдова', en: 'Moldova', zh: '摩尔多瓦' },
  { code: 'MC', ru: 'Монако', en: 'Monaco', zh: '摩纳哥' },
  { code: 'MN', ru: 'Монголия', en: 'Mongolia', zh: '蒙古' },
  { code: 'ME', ru: 'Черногория', en: 'Montenegro', zh: '黑山' },
  { code: 'MA', ru: 'Марокко', en: 'Morocco', zh: '摩洛哥' },
  { code: 'MZ', ru: 'Мозамбик', en: 'Mozambique', zh: '莫桑比克' },
  { code: 'MM', ru: 'Мьянма', en: 'Myanmar', zh: '缅甸' },
  { code: 'NA', ru: 'Намибия', en: 'Namibia', zh: '纳米比亚' },
  { code: 'NR', ru: 'Науру', en: 'Nauru', zh: '瑙鲁' },
  { code: 'NP', ru: 'Непал', en: 'Nepal', zh: '尼泊尔' },
  { code: 'NL', ru: 'Нидерланды', en: 'Netherlands', zh: '荷兰' },
  { code: 'NZ', ru: 'Новая Зеландия', en: 'New Zealand', zh: '新西兰' },
  { code: 'NI', ru: 'Никарагуа', en: 'Nicaragua', zh: '尼加拉瓜' },
  { code: 'NE', ru: 'Нигер', en: 'Niger', zh: '尼日尔' },
  { code: 'NG', ru: 'Нигерия', en: 'Nigeria', zh: '尼日利亚' },
  { code: 'MK', ru: 'Северная Македония', en: 'North Macedonia', zh: '北马其顿' },
  { code: 'NO', ru: 'Норвегия', en: 'Norway', zh: '挪威' },
  { code: 'OM', ru: 'Оман', en: 'Oman', zh: '阿曼' },
  { code: 'PK', ru: 'Пакистан', en: 'Pakistan', zh: '巴基斯坦' },
  { code: 'PW', ru: 'Палау', en: 'Palau', zh: '帕劳' },
  { code: 'PS', ru: 'Палестина', en: 'Palestine', zh: '巴勒斯坦' },
  { code: 'PA', ru: 'Панама', en: 'Panama', zh: '巴拿马' },
  { code: 'PG', ru: 'Папуа — Новая Гвинея', en: 'Papua New Guinea', zh: '巴布亚新几内亚' },
  { code: 'PY', ru: 'Парагвай', en: 'Paraguay', zh: '巴拉圭' },
  { code: 'PE', ru: 'Перу', en: 'Peru', zh: '秘鲁' },
  { code: 'PH', ru: 'Филиппины', en: 'Philippines', zh: '菲律宾' },
  { code: 'PL', ru: 'Польша', en: 'Poland', zh: '波兰' },
  { code: 'PT', ru: 'Португалия', en: 'Portugal', zh: '葡萄牙' },
  { code: 'QA', ru: 'Катар', en: 'Qatar', zh: '卡塔尔' },
  { code: 'RO', ru: 'Румыния', en: 'Romania', zh: '罗马尼亚' },
  { code: 'RU', ru: 'Россия', en: 'Russia', zh: '俄罗斯' },
  { code: 'RW', ru: 'Руанда', en: 'Rwanda', zh: '卢旺达' },
  { code: 'KN', ru: 'Сент-Китс и Невис', en: 'Saint Kitts and Nevis', zh: '圣基茨和尼维斯' },
  { code: 'LC', ru: 'Сент-Люсия', en: 'Saint Lucia', zh: '圣卢西亚' },
  { code: 'VC', ru: 'Сент-Винсент и Гренадины', en: 'Saint Vincent and the Grenadines', zh: '圣文森特和格林纳丁斯' },
  { code: 'WS', ru: 'Самоа', en: 'Samoa', zh: '萨摩亚' },
  { code: 'SM', ru: 'Сан-Марино', en: 'San Marino', zh: '圣马力诺' },
  { code: 'ST', ru: 'Сан-Томе и Принсипи', en: 'Sao Tome and Principe', zh: '圣多美和普林西比' },
  { code: 'SA', ru: 'Саудовская Аравия', en: 'Saudi Arabia', zh: '沙特阿拉伯' },
  { code: 'SN', ru: 'Сенегал', en: 'Senegal', zh: '塞内加尔' },
  { code: 'RS', ru: 'Сербия', en: 'Serbia', zh: '塞尔维亚' },
  { code: 'SC', ru: 'Сейшельские острова', en: 'Seychelles', zh: '塞舌尔' },
  { code: 'SL', ru: 'Сьерра-Леоне', en: 'Sierra Leone', zh: '塞拉利昂' },
  { code: 'SG', ru: 'Сингапур', en: 'Singapore', zh: '新加坡' },
  { code: 'SK', ru: 'Словакия', en: 'Slovakia', zh: '斯洛伐克' },
  { code: 'SI', ru: 'Словения', en: 'Slovenia', zh: '斯洛文尼亚' },
  { code: 'SB', ru: 'Соломоновы Острова', en: 'Solomon Islands', zh: '所罗门群岛' },
  { code: 'SO', ru: 'Сомали', en: 'Somalia', zh: '索马里' },
  { code: 'ZA', ru: 'ЮАР', en: 'South Africa', zh: '南非' },
  { code: 'SS', ru: 'Южный Судан', en: 'South Sudan', zh: '南苏丹' },
  { code: 'ES', ru: 'Испания', en: 'Spain', zh: '西班牙' },
  { code: 'LK', ru: 'Шри-Ланка', en: 'Sri Lanka', zh: '斯里兰卡' },
  { code: 'SD', ru: 'Судан', en: 'Sudan', zh: '苏丹' },
  { code: 'SR', ru: 'Суринам', en: 'Suriname', zh: '苏里南' },
  { code: 'SE', ru: 'Швеция', en: 'Sweden', zh: '瑞典' },
  { code: 'CH', ru: 'Швейцария', en: 'Switzerland', zh: '瑞士' },
  { code: 'SY', ru: 'Сирия', en: 'Syria', zh: '叙利亚' },
  { code: 'TW', ru: 'Тайвань', en: 'Taiwan', zh: '中国台湾' },
  { code: 'TJ', ru: 'Таджикистан', en: 'Tajikistan', zh: '塔吉克斯坦' },
  { code: 'TZ', ru: 'Танзания', en: 'Tanzania', zh: '坦桑尼亚' },
  { code: 'TH', ru: 'Таиланд', en: 'Thailand', zh: '泰国' },
  { code: 'TL', ru: 'Тимор-Лесте', en: 'Timor-Leste', zh: '东帝汶' },
  { code: 'TG', ru: 'Того', en: 'Togo', zh: '多哥' },
  { code: 'TO', ru: 'Тонга', en: 'Tonga', zh: '汤加' },
  { code: 'TT', ru: 'Тринидад и Тобаго', en: 'Trinidad and Tobago', zh: '特立尼达和多巴哥' },
  { code: 'TN', ru: 'Тунис', en: 'Tunisia', zh: '突尼斯' },
  { code: 'TR', ru: 'Турция', en: 'Turkey', zh: '土耳其' },
  { code: 'TM', ru: 'Туркменистан', en: 'Turkmenistan', zh: '土库曼斯坦' },
  { code: 'TV', ru: 'Тувалу', en: 'Tuvalu', zh: '图瓦卢' },
  { code: 'UG', ru: 'Уганда', en: 'Uganda', zh: '乌干达' },
  { code: 'UA', ru: 'Украина', en: 'Ukraine', zh: '乌克兰' },
  { code: 'AE', ru: 'Объединённые Арабские Эмираты', en: 'United Arab Emirates', zh: '阿拉伯联合酋长国' },
  { code: 'GB', ru: 'Великобритания', en: 'United Kingdom', zh: '英国' },
  { code: 'US', ru: 'США', en: 'United States', zh: '美国' },
  { code: 'UY', ru: 'Уругвай', en: 'Uruguay', zh: '乌拉圭' },
  { code: 'UZ', ru: 'Узбекистан', en: 'Uzbekistan', zh: '乌兹别克斯坦' },
  { code: 'VU', ru: 'Вануату', en: 'Vanuatu', zh: '瓦努阿图' },
  { code: 'VA', ru: 'Ватикан', en: 'Vatican City', zh: '梵蒂冈' },
  { code: 'VE', ru: 'Венесуэла', en: 'Venezuela', zh: '委内瑞拉' },
  { code: 'VN', ru: 'Вьетнам', en: 'Vietnam', zh: '越南' },
  { code: 'YE', ru: 'Йемен', en: 'Yemen', zh: '也门' },
  { code: 'ZM', ru: 'Замбия', en: 'Zambia', zh: '赞比亚' },
  { code: 'ZW', ru: 'Зимбабве', en: 'Zimbabwe', zh: '津巴布韦' },
];

function collationLocale(lang: Lang): string {
  return lang === 'ru' ? 'ru' : lang === 'zh' ? 'zh' : 'en';
}

export function getCountries(lang: Lang): { code: string; name: string }[] {
  const locale = collationLocale(lang);
  return COUNTRIES.map((c) => ({ code: c.code, name: c[lang] })).sort((a, b) => a.name.localeCompare(b.name, locale));
}

export function getCountryName(code: string, lang: Lang): string {
  return COUNTRIES.find((c) => c.code === code)?.[lang] ?? code;
}
