import type { Lang } from './i18n';

// ISO 3166-1 alpha-2 codes with Russian and English display names, for the
// verification (KYC) country selector — every country is selectable.
const COUNTRIES: { code: string; ru: string; en: string }[] = [
  { code: 'AF', ru: 'Афганистан', en: 'Afghanistan' },
  { code: 'AL', ru: 'Албания', en: 'Albania' },
  { code: 'DZ', ru: 'Алжир', en: 'Algeria' },
  { code: 'AD', ru: 'Андорра', en: 'Andorra' },
  { code: 'AO', ru: 'Ангола', en: 'Angola' },
  { code: 'AG', ru: 'Антигуа и Барбуда', en: 'Antigua and Barbuda' },
  { code: 'AR', ru: 'Аргентина', en: 'Argentina' },
  { code: 'AM', ru: 'Армения', en: 'Armenia' },
  { code: 'AU', ru: 'Австралия', en: 'Australia' },
  { code: 'AT', ru: 'Австрия', en: 'Austria' },
  { code: 'AZ', ru: 'Азербайджан', en: 'Azerbaijan' },
  { code: 'BS', ru: 'Багамы', en: 'Bahamas' },
  { code: 'BH', ru: 'Бахрейн', en: 'Bahrain' },
  { code: 'BD', ru: 'Бангладеш', en: 'Bangladesh' },
  { code: 'BB', ru: 'Барбадос', en: 'Barbados' },
  { code: 'BY', ru: 'Беларусь', en: 'Belarus' },
  { code: 'BE', ru: 'Бельгия', en: 'Belgium' },
  { code: 'BZ', ru: 'Белиз', en: 'Belize' },
  { code: 'BJ', ru: 'Бенин', en: 'Benin' },
  { code: 'BT', ru: 'Бутан', en: 'Bhutan' },
  { code: 'BO', ru: 'Боливия', en: 'Bolivia' },
  { code: 'BA', ru: 'Босния и Герцеговина', en: 'Bosnia and Herzegovina' },
  { code: 'BW', ru: 'Ботсвана', en: 'Botswana' },
  { code: 'BR', ru: 'Бразилия', en: 'Brazil' },
  { code: 'BN', ru: 'Бруней', en: 'Brunei' },
  { code: 'BG', ru: 'Болгария', en: 'Bulgaria' },
  { code: 'BF', ru: 'Буркина-Фасо', en: 'Burkina Faso' },
  { code: 'BI', ru: 'Бурунди', en: 'Burundi' },
  { code: 'KH', ru: 'Камбоджа', en: 'Cambodia' },
  { code: 'CM', ru: 'Камерун', en: 'Cameroon' },
  { code: 'CA', ru: 'Канада', en: 'Canada' },
  { code: 'CV', ru: 'Кабо-Верде', en: 'Cape Verde' },
  { code: 'CF', ru: 'Центральноафриканская Республика', en: 'Central African Republic' },
  { code: 'TD', ru: 'Чад', en: 'Chad' },
  { code: 'CL', ru: 'Чили', en: 'Chile' },
  { code: 'CN', ru: 'Китай', en: 'China' },
  { code: 'CO', ru: 'Колумбия', en: 'Colombia' },
  { code: 'KM', ru: 'Коморские острова', en: 'Comoros' },
  { code: 'CG', ru: 'Конго', en: 'Congo' },
  { code: 'CD', ru: 'Демократическая Республика Конго', en: 'DR Congo' },
  { code: 'CR', ru: 'Коста-Рика', en: 'Costa Rica' },
  { code: 'CI', ru: "Кот-д'Ивуар", en: "Cote d'Ivoire" },
  { code: 'HR', ru: 'Хорватия', en: 'Croatia' },
  { code: 'CU', ru: 'Куба', en: 'Cuba' },
  { code: 'CY', ru: 'Кипр', en: 'Cyprus' },
  { code: 'CZ', ru: 'Чехия', en: 'Czechia' },
  { code: 'DK', ru: 'Дания', en: 'Denmark' },
  { code: 'DJ', ru: 'Джибути', en: 'Djibouti' },
  { code: 'DM', ru: 'Доминика', en: 'Dominica' },
  { code: 'DO', ru: 'Доминиканская Республика', en: 'Dominican Republic' },
  { code: 'EC', ru: 'Эквадор', en: 'Ecuador' },
  { code: 'EG', ru: 'Египет', en: 'Egypt' },
  { code: 'SV', ru: 'Сальвадор', en: 'El Salvador' },
  { code: 'GQ', ru: 'Экваториальная Гвинея', en: 'Equatorial Guinea' },
  { code: 'ER', ru: 'Эритрея', en: 'Eritrea' },
  { code: 'EE', ru: 'Эстония', en: 'Estonia' },
  { code: 'SZ', ru: 'Эсватини', en: 'Eswatini' },
  { code: 'ET', ru: 'Эфиопия', en: 'Ethiopia' },
  { code: 'FJ', ru: 'Фиджи', en: 'Fiji' },
  { code: 'FI', ru: 'Финляндия', en: 'Finland' },
  { code: 'FR', ru: 'Франция', en: 'France' },
  { code: 'GA', ru: 'Габон', en: 'Gabon' },
  { code: 'GM', ru: 'Гамбия', en: 'Gambia' },
  { code: 'GE', ru: 'Грузия', en: 'Georgia' },
  { code: 'DE', ru: 'Германия', en: 'Germany' },
  { code: 'GH', ru: 'Гана', en: 'Ghana' },
  { code: 'GR', ru: 'Греция', en: 'Greece' },
  { code: 'GD', ru: 'Гренада', en: 'Grenada' },
  { code: 'GT', ru: 'Гватемала', en: 'Guatemala' },
  { code: 'GN', ru: 'Гвинея', en: 'Guinea' },
  { code: 'GW', ru: 'Гвинея-Бисау', en: 'Guinea-Bissau' },
  { code: 'GY', ru: 'Гайана', en: 'Guyana' },
  { code: 'HT', ru: 'Гаити', en: 'Haiti' },
  { code: 'HN', ru: 'Гондурас', en: 'Honduras' },
  { code: 'HK', ru: 'Гонконг', en: 'Hong Kong' },
  { code: 'HU', ru: 'Венгрия', en: 'Hungary' },
  { code: 'IS', ru: 'Исландия', en: 'Iceland' },
  { code: 'IN', ru: 'Индия', en: 'India' },
  { code: 'ID', ru: 'Индонезия', en: 'Indonesia' },
  { code: 'IR', ru: 'Иран', en: 'Iran' },
  { code: 'IQ', ru: 'Ирак', en: 'Iraq' },
  { code: 'IE', ru: 'Ирландия', en: 'Ireland' },
  { code: 'IL', ru: 'Израиль', en: 'Israel' },
  { code: 'IT', ru: 'Италия', en: 'Italy' },
  { code: 'JM', ru: 'Ямайка', en: 'Jamaica' },
  { code: 'JP', ru: 'Япония', en: 'Japan' },
  { code: 'JO', ru: 'Иордания', en: 'Jordan' },
  { code: 'KZ', ru: 'Казахстан', en: 'Kazakhstan' },
  { code: 'KE', ru: 'Кения', en: 'Kenya' },
  { code: 'KI', ru: 'Кирибати', en: 'Kiribati' },
  { code: 'KP', ru: 'Северная Корея', en: 'North Korea' },
  { code: 'KR', ru: 'Южная Корея', en: 'South Korea' },
  { code: 'XK', ru: 'Косово', en: 'Kosovo' },
  { code: 'KW', ru: 'Кувейт', en: 'Kuwait' },
  { code: 'KG', ru: 'Киргизстан', en: 'Kyrgyzstan' },
  { code: 'LA', ru: 'Лаос', en: 'Laos' },
  { code: 'LV', ru: 'Латвия', en: 'Latvia' },
  { code: 'LB', ru: 'Ливан', en: 'Lebanon' },
  { code: 'LS', ru: 'Лесото', en: 'Lesotho' },
  { code: 'LR', ru: 'Либерия', en: 'Liberia' },
  { code: 'LY', ru: 'Ливия', en: 'Libya' },
  { code: 'LI', ru: 'Лихтенштейн', en: 'Liechtenstein' },
  { code: 'LT', ru: 'Литва', en: 'Lithuania' },
  { code: 'LU', ru: 'Люксембург', en: 'Luxembourg' },
  { code: 'MO', ru: 'Макао', en: 'Macau' },
  { code: 'MG', ru: 'Мадагаскар', en: 'Madagascar' },
  { code: 'MW', ru: 'Малави', en: 'Malawi' },
  { code: 'MY', ru: 'Малайзия', en: 'Malaysia' },
  { code: 'MV', ru: 'Мальдивы', en: 'Maldives' },
  { code: 'ML', ru: 'Мали', en: 'Mali' },
  { code: 'MT', ru: 'Мальта', en: 'Malta' },
  { code: 'MH', ru: 'Маршалловы Острова', en: 'Marshall Islands' },
  { code: 'MR', ru: 'Мавритания', en: 'Mauritania' },
  { code: 'MU', ru: 'Маврикий', en: 'Mauritius' },
  { code: 'MX', ru: 'Мексика', en: 'Mexico' },
  { code: 'FM', ru: 'Микронезия', en: 'Micronesia' },
  { code: 'MD', ru: 'Молдова', en: 'Moldova' },
  { code: 'MC', ru: 'Монако', en: 'Monaco' },
  { code: 'MN', ru: 'Монголия', en: 'Mongolia' },
  { code: 'ME', ru: 'Черногория', en: 'Montenegro' },
  { code: 'MA', ru: 'Марокко', en: 'Morocco' },
  { code: 'MZ', ru: 'Мозамбик', en: 'Mozambique' },
  { code: 'MM', ru: 'Мьянма', en: 'Myanmar' },
  { code: 'NA', ru: 'Намибия', en: 'Namibia' },
  { code: 'NR', ru: 'Науру', en: 'Nauru' },
  { code: 'NP', ru: 'Непал', en: 'Nepal' },
  { code: 'NL', ru: 'Нидерланды', en: 'Netherlands' },
  { code: 'NZ', ru: 'Новая Зеландия', en: 'New Zealand' },
  { code: 'NI', ru: 'Никарагуа', en: 'Nicaragua' },
  { code: 'NE', ru: 'Нигер', en: 'Niger' },
  { code: 'NG', ru: 'Нигерия', en: 'Nigeria' },
  { code: 'MK', ru: 'Северная Македония', en: 'North Macedonia' },
  { code: 'NO', ru: 'Норвегия', en: 'Norway' },
  { code: 'OM', ru: 'Оман', en: 'Oman' },
  { code: 'PK', ru: 'Пакистан', en: 'Pakistan' },
  { code: 'PW', ru: 'Палау', en: 'Palau' },
  { code: 'PS', ru: 'Палестина', en: 'Palestine' },
  { code: 'PA', ru: 'Панама', en: 'Panama' },
  { code: 'PG', ru: 'Папуа — Новая Гвинея', en: 'Papua New Guinea' },
  { code: 'PY', ru: 'Парагвай', en: 'Paraguay' },
  { code: 'PE', ru: 'Перу', en: 'Peru' },
  { code: 'PH', ru: 'Филиппины', en: 'Philippines' },
  { code: 'PL', ru: 'Польша', en: 'Poland' },
  { code: 'PT', ru: 'Португалия', en: 'Portugal' },
  { code: 'QA', ru: 'Катар', en: 'Qatar' },
  { code: 'RO', ru: 'Румыния', en: 'Romania' },
  { code: 'RU', ru: 'Россия', en: 'Russia' },
  { code: 'RW', ru: 'Руанда', en: 'Rwanda' },
  { code: 'KN', ru: 'Сент-Китс и Невис', en: 'Saint Kitts and Nevis' },
  { code: 'LC', ru: 'Сент-Люсия', en: 'Saint Lucia' },
  { code: 'VC', ru: 'Сент-Винсент и Гренадины', en: 'Saint Vincent and the Grenadines' },
  { code: 'WS', ru: 'Самоа', en: 'Samoa' },
  { code: 'SM', ru: 'Сан-Марино', en: 'San Marino' },
  { code: 'ST', ru: 'Сан-Томе и Принсипи', en: 'Sao Tome and Principe' },
  { code: 'SA', ru: 'Саудовская Аравия', en: 'Saudi Arabia' },
  { code: 'SN', ru: 'Сенегал', en: 'Senegal' },
  { code: 'RS', ru: 'Сербия', en: 'Serbia' },
  { code: 'SC', ru: 'Сейшельские острова', en: 'Seychelles' },
  { code: 'SL', ru: 'Сьерра-Леоне', en: 'Sierra Leone' },
  { code: 'SG', ru: 'Сингапур', en: 'Singapore' },
  { code: 'SK', ru: 'Словакия', en: 'Slovakia' },
  { code: 'SI', ru: 'Словения', en: 'Slovenia' },
  { code: 'SB', ru: 'Соломоновы Острова', en: 'Solomon Islands' },
  { code: 'SO', ru: 'Сомали', en: 'Somalia' },
  { code: 'ZA', ru: 'ЮАР', en: 'South Africa' },
  { code: 'SS', ru: 'Южный Судан', en: 'South Sudan' },
  { code: 'ES', ru: 'Испания', en: 'Spain' },
  { code: 'LK', ru: 'Шри-Ланка', en: 'Sri Lanka' },
  { code: 'SD', ru: 'Судан', en: 'Sudan' },
  { code: 'SR', ru: 'Суринам', en: 'Suriname' },
  { code: 'SE', ru: 'Швеция', en: 'Sweden' },
  { code: 'CH', ru: 'Швейцария', en: 'Switzerland' },
  { code: 'SY', ru: 'Сирия', en: 'Syria' },
  { code: 'TW', ru: 'Тайвань', en: 'Taiwan' },
  { code: 'TJ', ru: 'Таджикистан', en: 'Tajikistan' },
  { code: 'TZ', ru: 'Танзания', en: 'Tanzania' },
  { code: 'TH', ru: 'Таиланд', en: 'Thailand' },
  { code: 'TL', ru: 'Тимор-Лесте', en: 'Timor-Leste' },
  { code: 'TG', ru: 'Того', en: 'Togo' },
  { code: 'TO', ru: 'Тонга', en: 'Tonga' },
  { code: 'TT', ru: 'Тринидад и Тобаго', en: 'Trinidad and Tobago' },
  { code: 'TN', ru: 'Тунис', en: 'Tunisia' },
  { code: 'TR', ru: 'Турция', en: 'Turkey' },
  { code: 'TM', ru: 'Туркменистан', en: 'Turkmenistan' },
  { code: 'TV', ru: 'Тувалу', en: 'Tuvalu' },
  { code: 'UG', ru: 'Уганда', en: 'Uganda' },
  { code: 'UA', ru: 'Украина', en: 'Ukraine' },
  { code: 'AE', ru: 'Объединённые Арабские Эмираты', en: 'United Arab Emirates' },
  { code: 'GB', ru: 'Великобритания', en: 'United Kingdom' },
  { code: 'US', ru: 'США', en: 'United States' },
  { code: 'UY', ru: 'Уругвай', en: 'Uruguay' },
  { code: 'UZ', ru: 'Узбекистан', en: 'Uzbekistan' },
  { code: 'VU', ru: 'Вануату', en: 'Vanuatu' },
  { code: 'VA', ru: 'Ватикан', en: 'Vatican City' },
  { code: 'VE', ru: 'Венесуэла', en: 'Venezuela' },
  { code: 'VN', ru: 'Вьетнам', en: 'Vietnam' },
  { code: 'YE', ru: 'Йемен', en: 'Yemen' },
  { code: 'ZM', ru: 'Замбия', en: 'Zambia' },
  { code: 'ZW', ru: 'Зимбабве', en: 'Zimbabwe' },
];

export function getCountries(lang: Lang): { code: string; name: string }[] {
  const locale = lang === 'ru' ? 'ru' : 'en';
  return COUNTRIES.map((c) => ({ code: c.code, name: c[lang] })).sort((a, b) => a.name.localeCompare(b.name, locale));
}

export function getCountryName(code: string, lang: Lang): string {
  return COUNTRIES.find((c) => c.code === code)?.[lang] ?? code;
}
