// ISO 3166-1 alpha-2 codes with Ukrainian display names, for the
// verification (KYC) country selector — every country is selectable.
export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'AF', name: 'Афганістан' },
  { code: 'AL', name: 'Албанія' },
  { code: 'DZ', name: 'Алжир' },
  { code: 'AD', name: 'Андорра' },
  { code: 'AO', name: 'Ангола' },
  { code: 'AG', name: 'Антигуа і Барбуда' },
  { code: 'AR', name: 'Аргентина' },
  { code: 'AM', name: 'Вірменія' },
  { code: 'AU', name: 'Австралія' },
  { code: 'AT', name: 'Австрія' },
  { code: 'AZ', name: 'Азербайджан' },
  { code: 'BS', name: 'Багами' },
  { code: 'BH', name: 'Бахрейн' },
  { code: 'BD', name: 'Бангладеш' },
  { code: 'BB', name: 'Барбадос' },
  { code: 'BY', name: 'Білорусь' },
  { code: 'BE', name: 'Бельгія' },
  { code: 'BZ', name: 'Беліз' },
  { code: 'BJ', name: 'Бенін' },
  { code: 'BT', name: 'Бутан' },
  { code: 'BO', name: 'Болівія' },
  { code: 'BA', name: 'Боснія і Герцеговина' },
  { code: 'BW', name: 'Ботсвана' },
  { code: 'BR', name: 'Бразилія' },
  { code: 'BN', name: 'Бруней' },
  { code: 'BG', name: 'Болгарія' },
  { code: 'BF', name: 'Буркіна-Фасо' },
  { code: 'BI', name: 'Бурунді' },
  { code: 'KH', name: 'Камбоджа' },
  { code: 'CM', name: 'Камерун' },
  { code: 'CA', name: 'Канада' },
  { code: 'CV', name: 'Кабо-Верде' },
  { code: 'CF', name: 'Центральноафриканська Республіка' },
  { code: 'TD', name: 'Чад' },
  { code: 'CL', name: 'Чилі' },
  { code: 'CN', name: 'Китай' },
  { code: 'CO', name: 'Колумбія' },
  { code: 'KM', name: 'Коморські Острови' },
  { code: 'CG', name: 'Конго' },
  { code: 'CD', name: 'Демократична Республіка Конго' },
  { code: 'CR', name: 'Коста-Рика' },
  { code: 'CI', name: "Кот-д'Івуар" },
  { code: 'HR', name: 'Хорватія' },
  { code: 'CU', name: 'Куба' },
  { code: 'CY', name: 'Кіпр' },
  { code: 'CZ', name: 'Чехія' },
  { code: 'DK', name: 'Данія' },
  { code: 'DJ', name: 'Джибуті' },
  { code: 'DM', name: 'Домініка' },
  { code: 'DO', name: 'Домініканська Республіка' },
  { code: 'EC', name: 'Еквадор' },
  { code: 'EG', name: 'Єгипет' },
  { code: 'SV', name: 'Сальвадор' },
  { code: 'GQ', name: 'Екваторіальна Гвінея' },
  { code: 'ER', name: 'Еритрея' },
  { code: 'EE', name: 'Естонія' },
  { code: 'SZ', name: 'Есватіні' },
  { code: 'ET', name: 'Ефіопія' },
  { code: 'FJ', name: 'Фіджі' },
  { code: 'FI', name: 'Фінляндія' },
  { code: 'FR', name: 'Франція' },
  { code: 'GA', name: 'Габон' },
  { code: 'GM', name: 'Гамбія' },
  { code: 'GE', name: 'Грузія' },
  { code: 'DE', name: 'Німеччина' },
  { code: 'GH', name: 'Гана' },
  { code: 'GR', name: 'Греція' },
  { code: 'GD', name: 'Гренада' },
  { code: 'GT', name: 'Гватемала' },
  { code: 'GN', name: 'Гвінея' },
  { code: 'GW', name: 'Гвінея-Бісау' },
  { code: 'GY', name: 'Гаяна' },
  { code: 'HT', name: 'Гаїті' },
  { code: 'HN', name: 'Гондурас' },
  { code: 'HK', name: 'Гонконг' },
  { code: 'HU', name: 'Угорщина' },
  { code: 'IS', name: 'Ісландія' },
  { code: 'IN', name: 'Індія' },
  { code: 'ID', name: 'Індонезія' },
  { code: 'IR', name: 'Іран' },
  { code: 'IQ', name: 'Ірак' },
  { code: 'IE', name: 'Ірландія' },
  { code: 'IL', name: 'Ізраїль' },
  { code: 'IT', name: 'Італія' },
  { code: 'JM', name: 'Ямайка' },
  { code: 'JP', name: 'Японія' },
  { code: 'JO', name: 'Йорданія' },
  { code: 'KZ', name: 'Казахстан' },
  { code: 'KE', name: 'Кенія' },
  { code: 'KI', name: 'Кірибаті' },
  { code: 'KP', name: 'Північна Корея' },
  { code: 'KR', name: 'Південна Корея' },
  { code: 'XK', name: 'Косово' },
  { code: 'KW', name: 'Кувейт' },
  { code: 'KG', name: 'Киргизстан' },
  { code: 'LA', name: 'Лаос' },
  { code: 'LV', name: 'Латвія' },
  { code: 'LB', name: 'Ліван' },
  { code: 'LS', name: 'Лесото' },
  { code: 'LR', name: 'Ліберія' },
  { code: 'LY', name: 'Лівія' },
  { code: 'LI', name: 'Ліхтенштейн' },
  { code: 'LT', name: 'Литва' },
  { code: 'LU', name: 'Люксембург' },
  { code: 'MO', name: 'Макао' },
  { code: 'MG', name: 'Мадагаскар' },
  { code: 'MW', name: 'Малаві' },
  { code: 'MY', name: 'Малайзія' },
  { code: 'MV', name: 'Мальдіви' },
  { code: 'ML', name: 'Малі' },
  { code: 'MT', name: 'Мальта' },
  { code: 'MH', name: 'Маршаллові Острови' },
  { code: 'MR', name: 'Мавританія' },
  { code: 'MU', name: 'Маврикій' },
  { code: 'MX', name: 'Мексика' },
  { code: 'FM', name: 'Мікронезія' },
  { code: 'MD', name: 'Молдова' },
  { code: 'MC', name: 'Монако' },
  { code: 'MN', name: 'Монголія' },
  { code: 'ME', name: 'Чорногорія' },
  { code: 'MA', name: 'Марокко' },
  { code: 'MZ', name: 'Мозамбік' },
  { code: 'MM', name: "М'янма" },
  { code: 'NA', name: 'Намібія' },
  { code: 'NR', name: 'Науру' },
  { code: 'NP', name: 'Непал' },
  { code: 'NL', name: 'Нідерланди' },
  { code: 'NZ', name: 'Нова Зеландія' },
  { code: 'NI', name: 'Нікарагуа' },
  { code: 'NE', name: 'Нігер' },
  { code: 'NG', name: 'Нігерія' },
  { code: 'MK', name: 'Північна Македонія' },
  { code: 'NO', name: 'Норвегія' },
  { code: 'OM', name: 'Оман' },
  { code: 'PK', name: 'Пакистан' },
  { code: 'PW', name: 'Палау' },
  { code: 'PS', name: 'Палестина' },
  { code: 'PA', name: 'Панама' },
  { code: 'PG', name: 'Папуа Нова Гвінея' },
  { code: 'PY', name: 'Парагвай' },
  { code: 'PE', name: 'Перу' },
  { code: 'PH', name: 'Філіппіни' },
  { code: 'PL', name: 'Польща' },
  { code: 'PT', name: 'Португалія' },
  { code: 'QA', name: 'Катар' },
  { code: 'RO', name: 'Румунія' },
  { code: 'RU', name: 'Росія' },
  { code: 'RW', name: 'Руанда' },
  { code: 'KN', name: 'Сент-Кітс і Невіс' },
  { code: 'LC', name: 'Сент-Люсія' },
  { code: 'VC', name: 'Сент-Вінсент і Гренадини' },
  { code: 'WS', name: 'Самоа' },
  { code: 'SM', name: 'Сан-Марино' },
  { code: 'ST', name: 'Сан-Томе і Принсіпі' },
  { code: 'SA', name: 'Саудівська Аравія' },
  { code: 'SN', name: 'Сенегал' },
  { code: 'RS', name: 'Сербія' },
  { code: 'SC', name: 'Сейшельські Острови' },
  { code: 'SL', name: 'Сьєрра-Леоне' },
  { code: 'SG', name: 'Сінгапур' },
  { code: 'SK', name: 'Словаччина' },
  { code: 'SI', name: 'Словенія' },
  { code: 'SB', name: 'Соломонові Острови' },
  { code: 'SO', name: 'Сомалі' },
  { code: 'ZA', name: 'Південно-Африканська Республіка' },
  { code: 'SS', name: 'Південний Судан' },
  { code: 'ES', name: 'Іспанія' },
  { code: 'LK', name: 'Шрі-Ланка' },
  { code: 'SD', name: 'Судан' },
  { code: 'SR', name: 'Суринам' },
  { code: 'SE', name: 'Швеція' },
  { code: 'CH', name: 'Швейцарія' },
  { code: 'SY', name: 'Сирія' },
  { code: 'TW', name: 'Тайвань' },
  { code: 'TJ', name: 'Таджикистан' },
  { code: 'TZ', name: 'Танзанія' },
  { code: 'TH', name: 'Таїланд' },
  { code: 'TL', name: 'Тимор-Лешті' },
  { code: 'TG', name: 'Того' },
  { code: 'TO', name: 'Тонга' },
  { code: 'TT', name: 'Тринідад і Тобаго' },
  { code: 'TN', name: 'Туніс' },
  { code: 'TR', name: 'Туреччина' },
  { code: 'TM', name: 'Туркменістан' },
  { code: 'TV', name: 'Тувалу' },
  { code: 'UG', name: 'Уганда' },
  { code: 'UA', name: 'Україна' },
  { code: 'AE', name: "Об'єднані Арабські Емірати" },
  { code: 'GB', name: 'Велика Британія' },
  { code: 'US', name: 'США' },
  { code: 'UY', name: 'Уругвай' },
  { code: 'UZ', name: 'Узбекистан' },
  { code: 'VU', name: 'Вануату' },
  { code: 'VA', name: 'Ватикан' },
  { code: 'VE', name: 'Венесуела' },
  { code: 'VN', name: "В'єтнам" },
  { code: 'YE', name: 'Ємен' },
  { code: 'ZM', name: 'Замбія' },
  { code: 'ZW', name: 'Зімбабве' },
].sort((a, b) => a.name.localeCompare(b.name, 'uk'));
