import React from 'react';
import type { Tone } from '../../data/market';
import { toneClass } from '../../utils/tone';

export function Eyebrow({ children, className = 'text-faint' }: {children: React.ReactNode;className?: string;}) { return <span className={`eyebrow block ${className}`}>{children}</span>; }
export function StatRow({ label, value, tone, note }: {label:string;value:string;tone?:Tone;note?:string;}) { return <div className="flex items-baseline justify-between gap-4 border-b border-line/70 py-2.5 last:border-b-0"><span className="text-[12px] leading-4 text-muted">{label}</span><span className="flex items-baseline gap-2 text-right"><span className={`num text-[13px] font-medium ${toneClass(tone)}`}>{value}</span>{note && <span className="text-[11px] text-faint">{note}</span>}</span></div>; }
export function Metric({ label, value, tone, size='md' }: {label:string;value:string;tone?:Tone;size?:'md'|'lg';}) { return <div><Eyebrow>{label}</Eyebrow><p className={`num mt-2 font-medium ${toneClass(tone)} ${size==='lg'?'text-[26px] leading-8':'text-[19px] leading-6'}`}>{value}</p></div>; }
type SegmentedProps={options:readonly string[];value:string;onChange:(value:string)=>void;size?:'sm'|'md';label?:string};
export function Segmented({options,value,onChange,size='md',label}:SegmentedProps){return <div role="tablist" aria-label={label} className="inline-flex border border-line bg-white p-[3px]">{options.map(option=>{const active=option===value;return <button key={option} type="button" role="tab" aria-selected={active} onClick={()=>onChange(option)} className={`px-3 font-medium transition-colors duration-150 ease-out ${size==='sm'?'h-6 text-[11px]':'h-7 text-[12px]'} ${active?'bg-accent-soft text-accent':'text-muted hover:text-ink'}`}>{option}</button>})}</div>}
export function Bar({value,max=100,color='bg-accent',track='bg-line',height='h-1.5'}:{value:number;max?:number;color?:string;track?:string;height?:string;}){return <div className={`w-full ${track} ${height}`}><div className={`${color} ${height} transition-[width] duration-300 ease-out`} style={{width:`${Math.min(100,value/max*100)}%`}} /></div>}
export function InfoDot({hint}:{hint:string}){return <span className="group relative inline-flex"><span tabIndex={0} role="button" aria-label={hint} className="flex h-[18px] w-[18px] items-center justify-center rounded-full border border-ink-line text-[10px] font-medium text-ink-mute outline-none transition-colors duration-150 ease-out hover:border-accent-bright hover:text-accent-bright focus-visible:border-accent-bright focus-visible:text-accent-bright">i</span><span className="pointer-events-none absolute left-0 top-6 z-20 w-56 border border-ink-line bg-ink-soft px-3 py-2 text-[11px] leading-[1.5] text-ink-mute opacity-0 transition-opacity duration-150 ease-out group-hover:opacity-100 group-focus-within:opacity-100">{hint}</span></span>}
